apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: aqp-core
  namespace: aqp
  labels:
    app.kubernetes.io/part-of: aqp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aqp-core
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
