apiVersion: v1
kind: Namespace
metadata:
  name: aqp
  labels:
    app.kubernetes.io/part-of: aqp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/environment: tower-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: aqp-admin
  labels:
    app.kubernetes.io/part-of: aqp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/environment: tower-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: aqp-data-services
  labels:
    app.kubernetes.io/part-of: aqp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/environment: tower-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: aqp-timeseries
  labels:
    app.kubernetes.io/part-of: aqp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/environment: tower-dev
