"""TorchServe adapter.

Packages a PyTorch model into a ``.mar`` archive and registers it with a
running TorchServe instance via the management API. The default handler
(:class:`AqpBaseHandler`) expects a pickled :class:`aqp.ml.base.BaseModel`
with an attached :class:`aqp.ml.processors.PreprocessingSpec` so the model
can reapply the exact preprocessing chain at inference time.

The adapter covers three common flows:

1. Launch a local TorchServe from scratch (``torchserve --start``).
2. Package + register a new ``.mar`` with an existing TorchServe.
3. Scale / unregister an existing model.
"""
from __future__ import annotations

import logging
import shutil
import subprocess
from pathlib import Path
from typing import Any

from aqp.config import settings
from aqp.core.registry import serving
from aqp.mlops.serving.base import (
    DeploymentInfo,
    ModelDeployment,
    PreparedModel,
    _spawn,
)

logger = logging.getLogger(__name__)


_DEFAULT_HANDLER = """\
# Auto-generated by aqp.mlops.serving.torchserve
import base64
import json
import logging
import pickle
from pathlib import Path

from ts.torch_handler.base_handler import BaseHandler


logger = logging.getLogger(__name__)


class AqpBaseHandler(BaseHandler):
    \"\"\"Loads an AQP Model pickle and its PreprocessingSpec, then delegates
    to ``model.predict``. Accepts JSON bodies shaped like ``{"dataframe_records": [...]}``
    or a plain list of records.\"\"\"

    def initialize(self, ctx):
        properties = ctx.system_properties
        model_dir = Path(properties.get("model_dir"))
        pkl = next(model_dir.glob("*.pkl"), None)
        if pkl is None:
            raise FileNotFoundError(f"No .pkl model artifact found in {model_dir}")
        with open(pkl, "rb") as fh:
            self.model = pickle.load(fh)
        self.spec = getattr(self.model, "preprocessing_spec", None)
        self.initialized = True

    def preprocess(self, requests):
        rows = []
        for req in requests:
            body = req.get("body") or req.get("data") or b""
            if isinstance(body, (bytes, bytearray)):
                body = body.decode("utf-8", "replace")
            try:
                payload = json.loads(body) if isinstance(body, str) else body
            except Exception:
                payload = {}
            if isinstance(payload, list):
                rows.extend(payload)
            elif isinstance(payload, dict):
                rows.extend(payload.get("dataframe_records") or [])
        import pandas as pd
        df = pd.DataFrame(rows)
        if self.spec is not None and hasattr(self.spec, "apply"):
            try:
                df = self.spec.apply(df)
            except Exception:
                logger.exception("preprocessing-spec apply failed")
        return df

    def inference(self, data):
        return self.model.predict(data) if hasattr(self.model, "predict") else []

    def postprocess(self, inference_output):
        try:
            return [inference_output.tolist()]
        except AttributeError:
            return [list(inference_output)]
"""


@serving("TorchServe")
class TorchServeDeployment(ModelDeployment):
    backend_name = "torchserve"

    def __init__(
        self,
        inference_url: str | None = None,
        management_url: str | None = None,
        model_store: Path | None = None,
        handler: str | None = None,
        batch_size: int = 1,
        max_batch_delay_ms: int = 100,
        initial_workers: int = 1,
    ) -> None:
        self.inference_url = inference_url or settings.torchserve_inference_url
        self.management_url = management_url or settings.torchserve_management_url
        self.model_store = Path(model_store or settings.torchserve_model_store)
        self.handler = handler  # path to .py; falls back to _DEFAULT_HANDLER
        self.batch_size = int(batch_size)
        self.max_batch_delay_ms = int(max_batch_delay_ms)
        self.initial_workers = int(initial_workers)
        self._server_proc: subprocess.Popen[str] | None = None

    # ------------------------------------------------------------------
    # Server lifecycle (optional — the user can run torchserve themselves).
    # ------------------------------------------------------------------

    def start_server(self) -> subprocess.Popen[str]:
        self.model_store.mkdir(parents=True, exist_ok=True)
        argv = [
            "torchserve",
            "--start",
            "--model-store",
            str(self.model_store),
            "--ncs",
        ]
        self._server_proc = _spawn(argv)
        return self._server_proc

    def stop_server(self) -> bool:
        try:
            subprocess.run(["torchserve", "--stop"], check=False, timeout=30)
            return True
        except Exception:
            logger.exception("torchserve --stop failed")
            return False

    # ------------------------------------------------------------------
    # Deploy flow
    # ------------------------------------------------------------------

    def _write_default_handler(self, dest: Path) -> Path:
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(_DEFAULT_HANDLER, encoding="utf-8")
        return dest

    def package_mar(
        self,
        model: PreparedModel,
        model_name: str,
        version: str = "1.0",
        export_dir: Path | None = None,
    ) -> Path:
        """Package ``model`` into ``<export_dir>/<model_name>.mar``."""
        if model.local_path is None:
            raise RuntimeError("TorchServe requires a local_path; resolve_model first")
        export_dir = Path(export_dir or self.model_store)
        export_dir.mkdir(parents=True, exist_ok=True)

        handler_path = (
            Path(self.handler)
            if self.handler
            else self._write_default_handler(export_dir / f"{model_name}_handler.py")
        )

        # Copy model pickle into a flat workspace.
        workdir = export_dir / f"{model_name}_pkg"
        if workdir.exists():
            shutil.rmtree(workdir)
        workdir.mkdir(parents=True)
        pkl_dest = workdir / Path(model.local_path).name
        shutil.copy(model.local_path, pkl_dest)
        handler_dest = workdir / handler_path.name
        shutil.copy(handler_path, handler_dest)

        argv = [
            "torch-model-archiver",
            "--model-name",
            model_name,
            "--version",
            version,
            "--serialized-file",
            str(pkl_dest),
            "--handler",
            str(handler_dest),
            "--export-path",
            str(export_dir),
            "--force",
        ]
        subprocess.run(argv, check=True)
        return export_dir / f"{model_name}.mar"

    def register(self, mar_path: Path, model_name: str, **kwargs: Any) -> bool:
        try:
            import httpx

            params = {
                "url": mar_path.name,
                "model_name": model_name,
                "initial_workers": kwargs.get("initial_workers", self.initial_workers),
                "batch_size": kwargs.get("batch_size", self.batch_size),
                "max_batch_delay": kwargs.get("max_batch_delay_ms", self.max_batch_delay_ms),
                "synchronous": "true",
            }
            r = httpx.post(
                f"{self.management_url}/models",
                params=params,
                timeout=30.0,
            )
            r.raise_for_status()
            return True
        except Exception:
            logger.exception("torchserve register failed")
            return False

    def deploy(self, model: PreparedModel, **kwargs: Any) -> DeploymentInfo:
        model_name = kwargs.get("model_name") or (model.name or "aqp-model")
        version = str(kwargs.get("version", "1.0"))
        mar = self.package_mar(model=model, model_name=model_name, version=version)
        registered = self.register(mar, model_name, **kwargs)
        endpoint = f"{self.inference_url.rstrip('/')}/predictions/{model_name}"
        return DeploymentInfo(
            backend=self.backend_name,
            endpoint_url=endpoint,
            process_name="torchserve",
            model_uri=model.model_uri,
            metadata={
                "model_name": model_name,
                "version": version,
                "mar_path": str(mar),
                "registered": bool(registered),
            },
        )

    def stop(self, info: DeploymentInfo) -> bool:
        try:
            import httpx

            model_name = info.metadata.get("model_name", "aqp-model")
            version = info.metadata.get("version", "1.0")
            r = httpx.delete(
                f"{self.management_url}/models/{model_name}/{version}",
                timeout=15.0,
            )
            return r.status_code < 400
        except Exception:
            logger.exception("torchserve unregister failed")
            return False


__all__ = ["TorchServeDeployment"]
