apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: aqp
  app.kubernetes.io/component: observability
  aqp.internal/canonical-owner: agentic_quant_platform

resources:
  - adot-collector.yaml
