apiVersion: v1
kind: Service
metadata:
  name: redpanda-connect
  namespace: aqp-streaming
  labels:
    app.kubernetes.io/name: redpanda-connect
    app.kubernetes.io/component: streaming
    app.kubernetes.io/part-of: aqp
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: redpanda-connect
  ports:
    - name: http
      port: 4195
      targetPort: 4195
      protocol: TCP
