portfolio_construction:
  class: EfficientCDaRPortfolio
  module_path: aqp.strategies.portfolio_opt.efficient_cdar
  kwargs:
    max_positions: 15
    long_only: true
    lookback_bars: 252
    beta: 0.95
    objective: min_cdar
