"""Execution Ledger, domain tables, and session persistence.

Importing this package triggers SQLAlchemy registration for every table
so ``Base.metadata`` and Alembic's autogenerate pick them up.
"""

from aqp.persistence.db import (
    AsyncSessionLocal,
    SessionLocal,
    async_engine,
    async_session_dep,
    engine,
    get_async_session,
    get_session,
)
from aqp.persistence.ledger import LedgerWriter
from aqp.persistence.models import (
    AgentRun,
    BacktestRun,
    Base,
    ChatMessage,
    DataLink,
    DataSource,
    DatasetCatalog,
    DatasetVersion,
    ExperimentPlan,
    Fill,
    FredSeries,
    GDeltMention,
    IdentifierLink,
    Instrument,
    LedgerEntry,
    ModelDeployment,
    ModelVersion,
    OrderRecord,
    PipelineRecipe,
    RLEpisode,
    SecFiling,
    Session,
    SignalEntry,
    SplitArtifact,
    SplitPlan,
    Strategy,
)
from aqp.persistence.models_agents import (
    AgentAnnotation,
    AgentEvalMetric,
    AgentEvaluation,
    AgentRunArtifact,
    AgentRunStep,
    AgentRunV2,
    AgentSpecRow,
    AgentSpecVersion,
)
from aqp.persistence.models_airbyte import (
    AirbyteConnectionRow,
    AirbyteConnectorRow,
    AirbyteSyncRunRow,
)
from aqp.persistence.models_dbt import (
    DbtModelVersionRow,
    DbtProjectRow,
    DbtRunRow,
    DbtSourceMappingRow,
)
from aqp.persistence.models_entities import (
    EntityRelationship,
    ExecutiveCompensation,
    Fund,
    GovernmentEntity,
    Industry,
    IndustryClassification,
    Issuer,
    KeyExecutive,
    Location,
    Sector,
)
from aqp.persistence.models_events import (
    AnalystEstimate,
    CalendarEventRow,
    CorporateEvent,
    DividendEventRow,
    EarningsEventRow,
    EsgEventRow,
    ForwardEstimate,
    IpoEventRow,
    MergerEventRow,
    PriceTarget,
    RegulatoryEventRow,
    SplitEventRow,
)
from aqp.persistence.models_fundamentals import (
    EarningsCallTranscript,
    FinancialRatios,
    FinancialStatement,
    HistoricalMarketCap,
    KeyMetrics,
    ManagementDiscussionAnalysis,
    ReportedFinancials,
    RevenueBreakdown,
)
from aqp.persistence.models_instruments import (
    InstrumentBetting,
    InstrumentBond,
    InstrumentCfd,
    InstrumentCommodity,
    InstrumentCrypto,
    InstrumentETF,
    InstrumentEquity,
    InstrumentFuture,
    InstrumentFxPair,
    InstrumentIndex,
    InstrumentOption,
    InstrumentSynthetic,
    InstrumentTokenizedAsset,
)
from aqp.persistence.models_macro import (
    BlsSeriesRow,
    CotReportRow,
    EconomicObservation,
    EconomicSeriesRow,
    FuturesCurveRow,
    MarketHolidayRow,
    MarketStatusHistory,
    OptionChainSnapshot,
    OptionSeries,
    TreasuryRateRow,
    YieldCurveRow,
)
from aqp.persistence.models_memory import (
    MemoryEpisode,
    MemoryOutcome,
    MemoryReflection,
)
from aqp.persistence.models_news import NewsItemEntity, NewsItemRow, NewsSentiment
from aqp.persistence.models_ownership import (
    Form13FHoldingRow,
    FundHolding,
    InsiderTransactionRow,
    InstitutionalHoldingRow,
    PoliticianTrade,
    SharesFloatSnapshot,
    ShortInterestSnapshot,
)
from aqp.persistence.models_rag import (
    RagChunkAudit,
    RagCorpus,
    RagDocument,
    RagEvalRun,
    RagQuery,
    RagSummary,
)
from aqp.persistence.models_regulatory import (
    CfpbComplaint,
    FdaAdverseEvent,
    FdaApplication,
    FdaRecall,
    UsptoAssignment,
    UsptoPatent,
    UsptoTrademark,
)
from aqp.persistence.models_taxonomy import (
    EntityCrosswalk,
    EntityTag,
    TaxonomyNode,
    TaxonomyScheme,
)
from aqp.persistence.models_pipelines import (
    DatahubSyncLog,
    DatasetProfile,
    FetcherRun,
    PipelineManifestRow,
    PipelineRunRow,
)
from aqp.persistence.models_entity_registry import (
    EntityAnnotation,
    EntityDatasetLink,
    EntityIdentifier,
    EntityRelation,
    EntityRow,
)

__all__ = [
    # Original core
    "AgentRun",
    "AsyncSessionLocal",
    "BacktestRun",
    "Base",
    "ChatMessage",
    "DataLink",
    "DataSource",
    "DatasetCatalog",
    "DatasetVersion",
    "ExperimentPlan",
    "Fill",
    "FredSeries",
    "GDeltMention",
    "IdentifierLink",
    "Instrument",
    "LedgerEntry",
    "LedgerWriter",
    "ModelDeployment",
    "ModelVersion",
    "OrderRecord",
    "PipelineRecipe",
    "RLEpisode",
    "SecFiling",
    "Session",
    "SessionLocal",
    "SignalEntry",
    "SplitArtifact",
    "SplitPlan",
    "Strategy",
    # Polymorphic instruments
    "InstrumentBetting",
    "InstrumentBond",
    "InstrumentCfd",
    "InstrumentCommodity",
    "InstrumentCrypto",
    "InstrumentETF",
    "InstrumentEquity",
    "InstrumentFuture",
    "InstrumentFxPair",
    "InstrumentIndex",
    "InstrumentOption",
    "InstrumentSynthetic",
    "InstrumentTokenizedAsset",
    # Entity graph
    "EntityRelationship",
    "ExecutiveCompensation",
    "Fund",
    "GovernmentEntity",
    "Industry",
    "IndustryClassification",
    "Issuer",
    "KeyExecutive",
    "Location",
    "Sector",
    # Fundamentals
    "EarningsCallTranscript",
    "FinancialRatios",
    "FinancialStatement",
    "HistoricalMarketCap",
    "KeyMetrics",
    "ManagementDiscussionAnalysis",
    "ReportedFinancials",
    "RevenueBreakdown",
    # Events / calendar
    "AnalystEstimate",
    "CalendarEventRow",
    "CorporateEvent",
    "DividendEventRow",
    "EarningsEventRow",
    "EsgEventRow",
    "ForwardEstimate",
    "IpoEventRow",
    "MergerEventRow",
    "PriceTarget",
    "RegulatoryEventRow",
    "SplitEventRow",
    # Ownership
    "Form13FHoldingRow",
    "FundHolding",
    "InsiderTransactionRow",
    "InstitutionalHoldingRow",
    "PoliticianTrade",
    "SharesFloatSnapshot",
    "ShortInterestSnapshot",
    # News
    "NewsItemEntity",
    "NewsItemRow",
    "NewsSentiment",
    # Macro / microstructure
    "BlsSeriesRow",
    "CotReportRow",
    "EconomicObservation",
    "EconomicSeriesRow",
    "FuturesCurveRow",
    "MarketHolidayRow",
    "MarketStatusHistory",
    "OptionChainSnapshot",
    "OptionSeries",
    "TreasuryRateRow",
    "YieldCurveRow",
    # Taxonomy
    "EntityCrosswalk",
    "EntityTag",
    "TaxonomyNode",
    "TaxonomyScheme",
    # Agents (Phase 3)
    "AgentAnnotation",
    "AgentEvalMetric",
    "AgentEvaluation",
    "AgentRunArtifact",
    "AgentRunStep",
    "AgentRunV2",
    "AgentSpecRow",
    "AgentSpecVersion",
    # Airbyte data fabric
    "AirbyteConnectionRow",
    "AirbyteConnectorRow",
    "AirbyteSyncRunRow",
    # dbt local modeling
    "DbtModelVersionRow",
    "DbtProjectRow",
    "DbtRunRow",
    "DbtSourceMappingRow",
    # RAG (Phase 3)
    "RagChunkAudit",
    "RagCorpus",
    "RagDocument",
    "RagEvalRun",
    "RagQuery",
    "RagSummary",
    # Memory (Phase 3)
    "MemoryEpisode",
    "MemoryOutcome",
    "MemoryReflection",
    # Regulatory (Phase 2)
    "CfpbComplaint",
    "FdaAdverseEvent",
    "FdaApplication",
    "FdaRecall",
    "UsptoAssignment",
    "UsptoPatent",
    "UsptoTrademark",
    # Data engine pipelines (Phase 3 — data-fabric expansion)
    "DatahubSyncLog",
    "DatasetProfile",
    "FetcherRun",
    "PipelineManifestRow",
    "PipelineRunRow",
    # Unified entity registry (Phase 4 — data-fabric expansion)
    "EntityAnnotation",
    "EntityDatasetLink",
    "EntityIdentifier",
    "EntityRelation",
    "EntityRow",
    # DB utilities
    "async_engine",
    "async_session_dep",
    "engine",
    "get_async_session",
    "get_session",
]
