"""Execution Ledger, domain tables, and session persistence.

Importing this package triggers SQLAlchemy registration for every table
so ``Base.metadata`` and Alembic's autogenerate pick them up.
"""

from aqp.persistence.db import (
    AsyncSessionLocal,
    SessionLocal,
    async_engine,
    async_session_dep,
    engine,
    get_async_session,
    get_session,
)
from aqp.persistence.ledger import LedgerWriter
from aqp.persistence.models import (
    AgentRun,
    BacktestRun,
    Base,
    ChatMessage,
    DataLink,
    DataSource,
    DatasetCatalog,
    DatasetVersion,
    ExperimentPlan,
    Fill,
    FredSeries,
    GDeltMention,
    IdentifierLink,
    Instrument,
    LedgerEntry,
    ModelDeployment,
    ModelVersion,
    OrderRecord,
    PipelineRecipe,
    RLEpisode,
    SecFiling,
    Session,
    SignalEntry,
    SplitArtifact,
    SplitPlan,
    Strategy,
)
from aqp.persistence.models_agents import (
    AgentAnnotation,
    AgentEvalMetric,
    AgentEvaluation,
    AgentRunArtifact,
    AgentRunStep,
    AgentRunV2,
    AgentSpecRow,
    AgentSpecVersion,
)
from aqp.persistence.models_assistants import (
    AssistantMessage,
    AssistantRun,
    AssistantRunEvent,
    AssistantSession,
    AssistantSkill,
    AssistantSpecRow,
    AssistantSpecVersion,
)
from aqp.persistence.models_bots import (
    Bot,
    BotDeployment,
    BotVersion,
)
from aqp.persistence.models_airbyte import (
    AirbyteConnectionRow,
    AirbyteConnectorRow,
    AirbyteSyncRunRow,
)
from aqp.persistence.models_dbt import (
    DbtModelVersionRow,
    DbtProjectRow,
    DbtRunRow,
    DbtSourceMappingRow,
)
from aqp.persistence.models_entities import (
    EntityRelationship,
    ExecutiveCompensation,
    Fund,
    GovernmentEntity,
    Industry,
    IndustryClassification,
    Issuer,
    KeyExecutive,
    Location,
    Sector,
)
from aqp.persistence.models_events import (
    AnalystEstimate,
    CalendarEventRow,
    CorporateEvent,
    DividendEventRow,
    EarningsEventRow,
    EsgEventRow,
    ForwardEstimate,
    IpoEventRow,
    MergerEventRow,
    PriceTarget,
    RegulatoryEventRow,
    SplitEventRow,
)
from aqp.persistence.models_fundamentals import (
    EarningsCallTranscript,
    FinancialRatios,
    FinancialStatement,
    HistoricalMarketCap,
    KeyMetrics,
    ManagementDiscussionAnalysis,
    ReportedFinancials,
    RevenueBreakdown,
)
from aqp.persistence.models_instruments import (
    InstrumentADR,
    InstrumentBetting,
    InstrumentBond,
    InstrumentCfd,
    InstrumentCommodity,
    InstrumentCrypto,
    InstrumentETF,
    InstrumentEquity,
    InstrumentFuture,
    InstrumentFxPair,
    InstrumentGDR,
    InstrumentIndex,
    InstrumentMeasure,
    InstrumentMutualFund,
    InstrumentOption,
    InstrumentOTCDerivative,
    InstrumentREIT,
    InstrumentSynthetic,
    InstrumentTokenizedAsset,
)
from aqp.persistence.models_macro import (
    BlsSeriesRow,
    CotReportRow,
    EconomicObservation,
    EconomicSeriesRow,
    FuturesCurveRow,
    MarketHolidayRow,
    MarketStatusHistory,
    OptionChainSnapshot,
    OptionSeries,
    TreasuryRateRow,
    YieldCurveRow,
)
from aqp.persistence.models_memory import (
    MemoryEpisode,
    MemoryOutcome,
    MemoryReflection,
)
from aqp.persistence.models_news import NewsItemEntity, NewsItemRow, NewsSentiment
from aqp.persistence.models_orders import (
    DomainOrderRow,
    ExecutionReportRow,
    OrderListRow,
)
from aqp.persistence.models_ownership import (
    Form13FHoldingRow,
    FundHolding,
    InsiderTransactionRow,
    InstitutionalHoldingRow,
    PoliticianTrade,
    SharesFloatSnapshot,
    ShortInterestSnapshot,
)
from aqp.persistence.models_rag import (
    RagChunkAudit,
    RagCorpus,
    RagDocument,
    RagEvalRun,
    RagQuery,
    RagSummary,
)
from aqp.persistence.models_regulatory import (
    CfpbComplaint,
    FdaAdverseEvent,
    FdaApplication,
    FdaRecall,
    UsptoAssignment,
    UsptoPatent,
    UsptoTrademark,
)
from aqp.persistence.models_rl import (
    RLComponentRegistration,
    RLEquityCurveRef,
    RLEvaluation,
    RLExperimentSpec as RLExperimentSpecRow,
    RLExperimentVersion,
    RLRun,
    RLTrajectoryRef,
)
from aqp.persistence.models_analysis import (
    AnalysisRun,
    AnalysisSpec as AnalysisSpecRow,
    AnalysisSpecVersion,
    AnalysisStepResult,
)
from aqp.persistence.models_taxonomy import (
    EntityCrosswalk,
    EntityTag,
    TaxonomyNode,
    TaxonomyScheme,
)
from aqp.persistence.models_tenancy import (
    ConfigOverlayRow,
    Lab,
    Membership,
    Organization,
    Project,
    Team,
    User,
    Workspace,
)
from aqp.persistence.models_experiments import (
    EXPERIMENT_KINDS,
    EXPERIMENT_STATUSES,
    Experiment,
    TEST_KINDS,
    Test,
)
from aqp.persistence.models_resources import (
    OWNER_SCOPE_KINDS,
    RESOURCE_RELATIONS,
    RESOURCE_TYPES,
    Resource,
    ResourceRelation,
)
from aqp.persistence.models_pipelines import (
    DatahubSyncLog,
    DatasetProfile,
    FetcherRun,
    PipelineManifestRow,
    PipelineRunRow,
)
from aqp.persistence.models_instrument_catalog import (
    CatalogFeedEdge,
    InstrumentCatalog,
)
from aqp.persistence.models_ingestion_ledger import (
    FabricVersionSnapshot,
    IngestionLedgerRow,
)
from aqp.persistence.models_entity_registry import (
    EntityAnnotation,
    EntityDatasetLink,
    EntityIdentifier,
    EntityRelation,
    EntityRow,
)
from aqp.persistence.models_data_control import (
    DatasetPipelineConfigRow,
    SourceLibraryEntry,
    SourceMetadataVersion,
)
from aqp.persistence.models_extraction import (
    DatasetPresetRow,
    ExtractionAuditRow,
)
from aqp.persistence.models_sinks import SinkRow, SinkVersionRow
from aqp.persistence.models_dagster_sandbox import DagsterSandboxSessionRow
from aqp.persistence.models_lab import (
    LAB_LABEL_KINDS,
    LAB_MODES,
    LAB_NODE_STATUSES,
    LAB_NOTE_TARGETS,
    LAB_RUN_STATUSES,
    LAB_SNIPPET_LANGS,
    LabArtifact,
    LabGraph,
    LabLabel,
    LabNodeRun,
    LabNote,
    LabPaperChunk,
    LabRun,
    LabSnippet,
)
from aqp.persistence.models_producers import MarketDataProducerRow
from aqp.persistence.models_streaming_links import StreamingDatasetLink
from aqp.persistence.models_lineage import DataLineageEvent
from aqp.persistence.models_terraform import (
    ENTRA_TENANT_STATUSES,
    EntraTenantLink,
    TERRAFORM_ENVIRONMENTS,
    TERRAFORM_MODULE_KINDS,
    TERRAFORM_PROVIDER_KINDS,
    TERRAFORM_RUN_KINDS,
    TERRAFORM_RUN_STATUSES,
    TERRAFORM_STATE_BACKENDS,
    TerraformPolicyAttachment,
    TerraformProvider,
    TerraformRun,
    TerraformStackSpecRow,
    TerraformStackSpecVersion,
    TerraformStateVersion,
    TerraformWorkspace,
)

__all__ = [
    # Original core
    "AgentRun",
    "AsyncSessionLocal",
    "BacktestRun",
    "Base",
    "ChatMessage",
    "DataLink",
    "DataSource",
    "DatasetCatalog",
    "DatasetVersion",
    "ExperimentPlan",
    "Fill",
    "FredSeries",
    "GDeltMention",
    "IdentifierLink",
    "Instrument",
    "LedgerEntry",
    "LedgerWriter",
    "ModelDeployment",
    "ModelVersion",
    "OrderRecord",
    "PipelineRecipe",
    "RLEpisode",
    "SecFiling",
    "Session",
    "SessionLocal",
    "SignalEntry",
    "SplitArtifact",
    "SplitPlan",
    "Strategy",
    # Polymorphic instruments
    "InstrumentADR",
    "InstrumentBetting",
    "InstrumentBond",
    "InstrumentCfd",
    "InstrumentCommodity",
    "InstrumentCrypto",
    "InstrumentETF",
    "InstrumentEquity",
    "InstrumentFuture",
    "InstrumentFxPair",
    "InstrumentGDR",
    "InstrumentIndex",
    "InstrumentMeasure",
    "InstrumentMutualFund",
    "InstrumentOption",
    "InstrumentOTCDerivative",
    "InstrumentREIT",
    "InstrumentSynthetic",
    "InstrumentTokenizedAsset",
    # Phase 2: unified domain orders + contingency graphs + execution reports
    "DomainOrderRow",
    "ExecutionReportRow",
    "OrderListRow",
    # Entity graph
    "EntityRelationship",
    "ExecutiveCompensation",
    "Fund",
    "GovernmentEntity",
    "Industry",
    "IndustryClassification",
    "Issuer",
    "KeyExecutive",
    "Location",
    "Sector",
    # Fundamentals
    "EarningsCallTranscript",
    "FinancialRatios",
    "FinancialStatement",
    "HistoricalMarketCap",
    "KeyMetrics",
    "ManagementDiscussionAnalysis",
    "ReportedFinancials",
    "RevenueBreakdown",
    # Events / calendar
    "AnalystEstimate",
    "CalendarEventRow",
    "CorporateEvent",
    "DividendEventRow",
    "EarningsEventRow",
    "EsgEventRow",
    "ForwardEstimate",
    "IpoEventRow",
    "MergerEventRow",
    "PriceTarget",
    "RegulatoryEventRow",
    "SplitEventRow",
    # Ownership
    "Form13FHoldingRow",
    "FundHolding",
    "InsiderTransactionRow",
    "InstitutionalHoldingRow",
    "PoliticianTrade",
    "SharesFloatSnapshot",
    "ShortInterestSnapshot",
    # News
    "NewsItemEntity",
    "NewsItemRow",
    "NewsSentiment",
    # Macro / microstructure
    "BlsSeriesRow",
    "CotReportRow",
    "EconomicObservation",
    "EconomicSeriesRow",
    "FuturesCurveRow",
    "MarketHolidayRow",
    "MarketStatusHistory",
    "OptionChainSnapshot",
    "OptionSeries",
    "TreasuryRateRow",
    "YieldCurveRow",
    # Taxonomy
    "EntityCrosswalk",
    "EntityTag",
    "TaxonomyNode",
    "TaxonomyScheme",
    # Tenancy (multi-tenant resource ownership)
    "ConfigOverlayRow",
    "Lab",
    "Membership",
    "Organization",
    "Project",
    "Team",
    "User",
    "Workspace",
    # Experiments / Tests umbrella (Phase 1 — multi-tenant graph)
    "EXPERIMENT_KINDS",
    "EXPERIMENT_STATUSES",
    "Experiment",
    "TEST_KINDS",
    "Test",
    # Polymorphic Resources (Phase 1 — multi-tenant graph)
    "OWNER_SCOPE_KINDS",
    "RESOURCE_RELATIONS",
    "RESOURCE_TYPES",
    "Resource",
    "ResourceRelation",
    # Agents (Phase 3)
    "AgentAnnotation",
    "AgentEvalMetric",
    "AgentEvaluation",
    "AgentRunArtifact",
    "AgentRunStep",
    "AgentRunV2",
    "AgentSpecRow",
    "AgentSpecVersion",
    # Assistant Engine
    "AssistantMessage",
    "AssistantRun",
    "AssistantRunEvent",
    "AssistantSession",
    "AssistantSkill",
    "AssistantSpecRow",
    "AssistantSpecVersion",
    # Bots (Bot Entity Refactor)
    "Bot",
    "BotDeployment",
    "BotVersion",
    # Airbyte data fabric
    "AirbyteConnectionRow",
    "AirbyteConnectorRow",
    "AirbyteSyncRunRow",
    # dbt local modeling
    "DbtModelVersionRow",
    "DbtProjectRow",
    "DbtRunRow",
    "DbtSourceMappingRow",
    # RAG (Phase 3)
    "RagChunkAudit",
    "RagCorpus",
    "RagDocument",
    "RagEvalRun",
    "RagQuery",
    "RagSummary",
    # Memory (Phase 3)
    "MemoryEpisode",
    "MemoryOutcome",
    "MemoryReflection",
    # Regulatory (Phase 2)
    "CfpbComplaint",
    "FdaAdverseEvent",
    "FdaApplication",
    "FdaRecall",
    "UsptoAssignment",
    "UsptoPatent",
    "UsptoTrademark",
    # RL layer (FinRL + FinRobot inspired refactor)
    "RLComponentRegistration",
    "RLEquityCurveRef",
    "RLEvaluation",
    "RLExperimentSpecRow",
    "RLExperimentVersion",
    "RLRun",
    "RLTrajectoryRef",
    # Analysis layer (research / diagnostic / production analyses)
    "AnalysisRun",
    "AnalysisSpecRow",
    "AnalysisSpecVersion",
    "AnalysisStepResult",
    # Data engine pipelines (Phase 3 — data-fabric expansion)
    "DatahubSyncLog",
    "DatasetProfile",
    "FetcherRun",
    "PipelineManifestRow",
    "PipelineRunRow",
    # Unified entity registry (Phase 4 — data-fabric expansion)
    "EntityAnnotation",
    "EntityDatasetLink",
    "EntityIdentifier",
    "EntityRelation",
    "EntityRow",
    # Data control plane (source library + project pipeline configs)
    "DatasetPipelineConfigRow",
    "SourceLibraryEntry",
    "SourceMetadataVersion",
    # Inspiration rehydration / dataset preset library
    "DatasetPresetRow",
    "ExtractionAuditRow",
    # Sinks / producers / streaming linkage (data layer expansion)
    "MarketDataProducerRow",
    "SinkRow",
    "SinkVersionRow",
    "StreamingDatasetLink",
    # Dagster sandbox (data fabric phase 3)
    "DagsterSandboxSessionRow",
    # Data Lab (foundation — 4-mode GraphSpec workspace)
    "LAB_LABEL_KINDS",
    "LAB_MODES",
    "LAB_NODE_STATUSES",
    "LAB_NOTE_TARGETS",
    "LAB_RUN_STATUSES",
    "LAB_SNIPPET_LANGS",
    "LabArtifact",
    "LabGraph",
    "LabLabel",
    "LabNodeRun",
    "LabNote",
    "LabPaperChunk",
    "LabRun",
    "LabSnippet",
    # Data lineage (Phase 2 - data layer unification)
    "DataLineageEvent",
    # Terraform IaC control plane + Entra ID tenant link
    "ENTRA_TENANT_STATUSES",
    "EntraTenantLink",
    "TERRAFORM_ENVIRONMENTS",
    "TERRAFORM_MODULE_KINDS",
    "TERRAFORM_PROVIDER_KINDS",
    "TERRAFORM_RUN_KINDS",
    "TERRAFORM_RUN_STATUSES",
    "TERRAFORM_STATE_BACKENDS",
    "TerraformPolicyAttachment",
    "TerraformProvider",
    "TerraformRun",
    "TerraformStackSpecRow",
    "TerraformStackSpecVersion",
    "TerraformStateVersion",
    "TerraformWorkspace",
    # Data fabric foundation (Phase 1)
    "CatalogFeedEdge",
    "FabricVersionSnapshot",
    "IngestionLedgerRow",
    "InstrumentCatalog",
    # DB utilities
    "async_engine",
    "async_session_dep",
    "engine",
    "get_async_session",
    "get_session",
]
