output "instance_endpoint" { value = aws_db_instance.this.endpoint }
output "instance_arn" { value = aws_db_instance.this.arn }
output "subnet_group" { value = aws_db_subnet_group.this.name }
output "security_group_id" { value = aws_security_group.this.id }
output "master_password_secret_arn" {
  description = "Master password is generated by Terraform; store in Secrets Manager out of band."
  value       = null
  sensitive   = true
}
