apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aqp-prod

resources:
  - ../../base

patches:
  - target:
      kind: ConfigMap
      name: aqp-env
    patch: |-
      - op: replace
        path: /data/AQP_ENV
        value: prod
      - op: replace
        path: /data/AQP_OTEL_SAMPLE_RATIO
        value: "0.1"
  - target:
      kind: Deployment
      name: worker
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
