apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonLabels:
  app.kubernetes.io/environment: staging

images:
  - name: docker.io/julian0215/aqp-client
    newTag: staging
  - name: docker.io/julian0215/aqp-api
    newTag: staging
  - name: docker.io/julian0215/aqp-worker
    newTag: staging
  - name: docker.io/julian0215/aqp-control-plane
    newTag: staging

patches:
  # Staging matches prod replica counts but smaller HPA ceilings.
  - target:
      kind: HorizontalPodAutoscaler
      name: aqp-client
    patch: |-
      - op: replace
        path: /spec/maxReplicas
        value: 6
  - target:
      kind: HorizontalPodAutoscaler
      name: aqp-core
    patch: |-
      - op: replace
        path: /spec/maxReplicas
        value: 5
  - target:
      kind: HorizontalPodAutoscaler
      name: aqp-worker
    patch: |-
      - op: replace
        path: /spec/maxReplicas
        value: 8
