// extract-python.ts — Griffe + griffe-pydantic + mdxify orchestrator.
//
// On every commit that touches **/*.py, Turbo runs this script. It
// shells out to `python -m mdxify` for each top-level package and
// emits MDX into `aqp_docs/docs/reference/python/<package>/`.
//
// The MDX output is consumed by Docusaurus on the next build.
//
// Hard rules respected:
//   - AGENTS rule 26 (CredentialResolver): no env vars are read here
//     except PY (which only locates the python binary).
//   - aqp-management-engine always-on: no token / Authorization
//     header / secret value is ever printed.

import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, rmSync } from 'node:fs';
import { join, resolve } from 'node:path';

const REPO_ROOT = resolve(__dirname, '..', '..');
const DOCS_OUTPUT_ROOT = join(REPO_ROOT, 'aqp_docs', 'docs', 'reference', 'python');

const PY = process.env.AQP_PYTHON ?? 'python';

type PackageSpec = {
  /** PyPI / module name, e.g. `aqp_rl`. */
  module: string;
  /** Path to add to sys.path so the module resolves. */
  searchPath: string;
  /** Where the MDX lands under docs/reference/python/. */
  outputDir: string;
};

const PACKAGES: PackageSpec[] = [
  {
    module: 'aqp',
    searchPath: REPO_ROOT,
    outputDir: 'aqp',
  },
  {
    module: 'aqp_rl',
    searchPath: join(REPO_ROOT, 'aqp_rl', 'src'),
    outputDir: 'aqp_rl',
  },
  {
    module: 'aqp_models',
    searchPath: join(REPO_ROOT, 'aqp_models', 'src'),
    outputDir: 'aqp_models',
  },
  {
    module: 'aqp_cp',
    searchPath: join(REPO_ROOT, 'aqp_control_plane', 'src'),
    outputDir: 'aqp_control_plane',
  },
  {
    module: 'aqp_platform_core',
    searchPath: join(REPO_ROOT, 'aqp_platform_core', 'src'),
    outputDir: 'aqp_platform_core',
  },
  {
    module: 'aqp_bots',
    searchPath: REPO_ROOT,
    outputDir: 'aqp_bots',
  },
];

function checkGriffeInstalled(): boolean {
  const result = spawnSync(PY, ['-c', 'import griffe, griffe_pydantic'], {
    stdio: 'pipe',
  });
  return result.status === 0;
}

function runMdxify(spec: PackageSpec): boolean {
  const outDir = join(DOCS_OUTPUT_ROOT, spec.outputDir);
  if (existsSync(outDir)) {
    rmSync(outDir, { recursive: true, force: true });
  }
  mkdirSync(outDir, { recursive: true });

  // mdxify --module <module> --search-path <path> --output-dir <out>
  // We invoke griffe directly when mdxify isn't installed; the
  // fallback emits a single index.mdx noting the missing dep.
  const result = spawnSync(
    PY,
    [
      '-m',
      'mdxify',
      '--module',
      spec.module,
      '--search-path',
      spec.searchPath,
      '--output-dir',
      outDir,
      '--docstring-style',
      'google',
      '--exclude-private',
      '--include-source-links',
      '--docusaurus-admonitions',
    ],
    { stdio: 'inherit' },
  );

  if (result.status !== 0) {
    console.warn(
      `[extract-python] mdxify failed for ${spec.module} (exit ${result.status}). Falling back to stub.`,
    );
    return false;
  }
  return true;
}

function writeStub(spec: PackageSpec): void {
  const outDir = join(DOCS_OUTPUT_ROOT, spec.outputDir);
  mkdirSync(outDir, { recursive: true });
  const today = new Date().toISOString().slice(0, 10);
  const fm = [
    '---',
    `title: '${spec.module}'`,
    `summary: 'Auto-generated reference for the ${spec.module} package. Re-runs on every PR touching **/*.py.'`,
    `owner: platform-team`,
    `last_reviewed: ${today}`,
    `audience: both`,
    '---',
    '',
    `# ${spec.module}`,
    '',
    'This page would normally be auto-generated by `mdxify` from the',
    'Python source. The extraction binary is not available in this',
    'environment — re-run `pnpm --filter aqp_docs extract-python` once',
    'griffe + griffe-pydantic + mdxify are installed:',
    '',
    '```powershell',
    'pip install "griffe>=1.5" "griffe-pydantic>=0.1.4" "mdxify>=0.1"',
    'pnpm --filter aqp_docs extract-python',
    '```',
    '',
    '## Source',
    '',
    `- Module: \`${spec.module}\``,
    `- Search path: \`${spec.searchPath}\``,
    '',
  ].join('\n');
  const fs = require('node:fs') as typeof import('node:fs');
  fs.writeFileSync(join(outDir, 'index.mdx'), fm, 'utf-8');
}

async function main(): Promise<void> {
  if (!checkGriffeInstalled()) {
    console.warn(
      '[extract-python] griffe + griffe-pydantic not installed. Emitting stubs only. Install with: pip install "griffe>=1.5" "griffe-pydantic>=0.1.4" "mdxify>=0.1"',
    );
    for (const pkg of PACKAGES) writeStub(pkg);
    return;
  }

  mkdirSync(DOCS_OUTPUT_ROOT, { recursive: true });
  for (const pkg of PACKAGES) {
    console.log(`[extract-python] extracting ${pkg.module}…`);
    const ok = runMdxify(pkg);
    if (!ok) writeStub(pkg);
  }
  console.log('[extract-python] done.');
}

void main();
