import {
  AppstoreOutlined,
  BulbOutlined,
  CloudUploadOutlined,
  CodeOutlined,
  DatabaseOutlined,
  DotChartOutlined,
  ExperimentOutlined,
  FolderOpenOutlined,
  FundOutlined,
  HomeOutlined,
  LineChartOutlined,
  MessageOutlined,
  MonitorOutlined,
  NodeIndexOutlined,
  PartitionOutlined,
  RobotOutlined,
  SettingOutlined,
  StockOutlined,
  ThunderboltOutlined,
  UnorderedListOutlined,
  WalletOutlined,
} from "@ant-design/icons";
import type { ReactNode } from "react";

export interface NavItem {
  key: string;
  label: string;
  href: string;
  icon: ReactNode;
  group: "Workspace" | "Research" | "Lab" | "Execution" | "Workflows" | "Agents" | "RAG" | "System";
  hotkey?: string;
}

export const NAV_ITEMS: NavItem[] = [
  { key: "home", label: "Dashboard", href: "/", icon: <HomeOutlined />, group: "Workspace" },
  { key: "chat", label: "Chat", href: "/chat", icon: <MessageOutlined />, group: "Workspace" },
  {
    key: "strategies",
    label: "Strategies",
    href: "/strategies",
    icon: <AppstoreOutlined />,
    group: "Research",
  },
  {
    key: "data-catalog",
    label: "Data Catalog",
    href: "/data/catalog",
    icon: <FolderOpenOutlined />,
    group: "Research",
  },
  {
    key: "data-iceberg",
    label: "Iceberg Editor",
    href: "/data/iceberg",
    icon: <PartitionOutlined />,
    group: "Research",
  },
  {
    key: "data-dbt",
    label: "dbt Models",
    href: "/data/dbt",
    icon: <CodeOutlined />,
    group: "Research",
  },
  {
    key: "data-ingest",
    label: "Data Ingest",
    href: "/data/ingest",
    icon: <CloudUploadOutlined />,
    group: "Research",
  },
  {
    key: "airbyte",
    label: "Airbyte",
    href: "/airbyte",
    icon: <CloudUploadOutlined />,
    group: "Research",
  },
  {
    key: "airbyte-connectors",
    label: "Airbyte Connectors",
    href: "/airbyte/connectors",
    icon: <DatabaseOutlined />,
    group: "Research",
  },
  {
    key: "airbyte-builder",
    label: "Airbyte Builder",
    href: "/airbyte/builder",
    icon: <ExperimentOutlined />,
    group: "Research",
  },
  {
    key: "airbyte-runs",
    label: "Airbyte Runs",
    href: "/airbyte/runs",
    icon: <MonitorOutlined />,
    group: "Research",
  },
  {
    key: "data-explorer",
    label: "Data Workspace",
    href: "/data/explorer",
    icon: <DatabaseOutlined />,
    group: "Research",
  },
  {
    key: "data-browser",
    label: "Data Browser",
    href: "/data/browser",
    icon: <StockOutlined />,
    group: "Research",
  },
  {
    key: "data-sources",
    label: "Sources",
    href: "/data/sources",
    icon: <PartitionOutlined />,
    group: "Research",
  },
  {
    key: "data-cfpb",
    label: "CFPB Complaints",
    href: "/data/cfpb",
    icon: <DatabaseOutlined />,
    group: "Research",
  },
  {
    key: "data-fda",
    label: "FDA",
    href: "/data/fda",
    icon: <DatabaseOutlined />,
    group: "Research",
  },
  {
    key: "data-uspto",
    label: "USPTO",
    href: "/data/uspto",
    icon: <DatabaseOutlined />,
    group: "Research",
  },
  {
    key: "data-indicators",
    label: "Indicator Catalog",
    href: "/data/indicators",
    icon: <ExperimentOutlined />,
    group: "Research",
  },
  {
    key: "alpha-vantage",
    label: "Alpha Vantage",
    href: "/alpha-vantage",
    icon: <LineChartOutlined />,
    group: "Research",
  },
  {
    key: "data-live",
    label: "Live Market",
    href: "/data/live",
    icon: <ThunderboltOutlined />,
    group: "Research",
  },
  {
    key: "factors",
    label: "Factor Workbench",
    href: "/factors",
    icon: <BulbOutlined />,
    group: "Research",
  },
  {
    key: "feature-sets",
    label: "Feature Sets",
    href: "/features",
    icon: <BulbOutlined />,
    group: "Research",
  },
  {
    key: "kg",
    label: "Knowledge Graph",
    href: "/data/kg",
    icon: <NodeIndexOutlined />,
    group: "Research",
  },
  {
    key: "research-equity",
    label: "Equity Research",
    href: "/research",
    icon: <BulbOutlined />,
    group: "Research",
  },
  {
    key: "learn",
    label: "Learn / Taxonomy",
    href: "/learn",
    icon: <BulbOutlined />,
    group: "Research",
  },
  {
    key: "backtest",
    label: "Backtests",
    href: "/backtest",
    icon: <LineChartOutlined />,
    group: "Lab",
  },
  {
    key: "optimizer",
    label: "Optimizer",
    href: "/optimizer",
    icon: <DotChartOutlined />,
    group: "Lab",
  },
  {
    key: "monte-carlo",
    label: "Monte Carlo",
    href: "/monte-carlo",
    icon: <ExperimentOutlined />,
    group: "Lab",
  },
  { key: "ml", label: "ML Training", href: "/ml/training", icon: <FundOutlined />, group: "Lab" },
  {
    key: "ml-datasets",
    label: "ML Datasets",
    href: "/ml/datasets",
    icon: <DatabaseOutlined />,
    group: "Lab",
  },
  {
    key: "ml-test",
    label: "ML Test",
    href: "/ml/test",
    icon: <ExperimentOutlined />,
    group: "Lab",
  },
  {
    key: "ml-models",
    label: "ML Models",
    href: "/ml/models",
    icon: <UnorderedListOutlined />,
    group: "Lab",
  },
  { key: "rl", label: "RL", href: "/rl", icon: <RobotOutlined />, group: "Lab" },
  {
    key: "paper",
    label: "Paper Runs",
    href: "/paper",
    icon: <ThunderboltOutlined />,
    group: "Execution",
  },
  {
    key: "portfolio",
    label: "Portfolio",
    href: "/portfolio",
    icon: <WalletOutlined />,
    group: "Execution",
  },
  {
    key: "monitor",
    label: "Monitor",
    href: "/monitor",
    icon: <MonitorOutlined />,
    group: "Execution",
  },
  {
    key: "crew",
    label: "Crew Trace",
    href: "/crew",
    icon: <RobotOutlined />,
    group: "Execution",
  },
  {
    key: "wf-agent",
    label: "Agent Crew Editor",
    href: "/workflows/agent",
    icon: <NodeIndexOutlined />,
    group: "Workflows",
  },
  {
    key: "wf-data",
    label: "Data Pipeline Editor",
    href: "/workflows/data",
    icon: <NodeIndexOutlined />,
    group: "Workflows",
  },
  {
    key: "wf-strategy",
    label: "Strategy Composer",
    href: "/workflows/strategy",
    icon: <NodeIndexOutlined />,
    group: "Workflows",
  },
  // -- Phase 7 of agentic-RAG expansion: Agents shell + RAG explorer ---
  {
    key: "agents-home",
    label: "Agents",
    href: "/agents",
    icon: <RobotOutlined />,
    group: "Agents",
  },
  {
    key: "agents-registry",
    label: "Agent Registry",
    href: "/agents/registry",
    icon: <UnorderedListOutlined />,
    group: "Agents",
  },
  {
    key: "agents-runs",
    label: "Agent Runs",
    href: "/agents/runs",
    icon: <MonitorOutlined />,
    group: "Agents",
  },
  {
    key: "agents-evaluations",
    label: "Evaluations",
    href: "/agents/evaluations",
    icon: <ExperimentOutlined />,
    group: "Agents",
  },
  {
    key: "agents-research",
    label: "Research Agents",
    href: "/agents/research",
    icon: <BulbOutlined />,
    group: "Agents",
  },
  {
    key: "agents-selection",
    label: "Selection Agent",
    href: "/agents/selection",
    icon: <AppstoreOutlined />,
    group: "Agents",
  },
  {
    key: "agents-trader",
    label: "Trader Agent",
    href: "/agents/trader",
    icon: <ThunderboltOutlined />,
    group: "Agents",
  },
  {
    key: "agents-analysis",
    label: "Analysis Agents",
    href: "/agents/analysis",
    icon: <DotChartOutlined />,
    group: "Agents",
  },
  {
    key: "rag-explorer",
    label: "RAG Explorer",
    href: "/rag",
    icon: <NodeIndexOutlined />,
    group: "RAG",
  },
  {
    key: "rag-admin",
    label: "RAG Admin",
    href: "/rag/admin",
    icon: <SettingOutlined />,
    group: "RAG",
  },
  {
    key: "models",
    label: "Models & Providers",
    href: "/models",
    icon: <RobotOutlined />,
    group: "System",
  },
  { key: "docs", label: "Docs", href: "/docs", icon: <BulbOutlined />, group: "System" },
  {
    key: "settings",
    label: "Settings",
    href: "/settings",
    icon: <SettingOutlined />,
    group: "System",
  },
];
