import {
  AppstoreOutlined,
  BulbOutlined,
  DatabaseOutlined,
  DotChartOutlined,
  ExperimentOutlined,
  FundOutlined,
  HomeOutlined,
  LineChartOutlined,
  MessageOutlined,
  MonitorOutlined,
  NodeIndexOutlined,
  PartitionOutlined,
  RobotOutlined,
  SettingOutlined,
  StockOutlined,
  ThunderboltOutlined,
  UnorderedListOutlined,
  WalletOutlined,
} from "@ant-design/icons";
import type { ReactNode } from "react";

export interface NavItem {
  key: string;
  label: string;
  href: string;
  icon: ReactNode;
  group: "Workspace" | "Research" | "Lab" | "Execution" | "Workflows" | "System";
  hotkey?: string;
}

export const NAV_ITEMS: NavItem[] = [
  { key: "home", label: "Dashboard", href: "/", icon: <HomeOutlined />, group: "Workspace" },
  { key: "chat", label: "Chat", href: "/chat", icon: <MessageOutlined />, group: "Workspace" },
  {
    key: "strategies",
    label: "Strategies",
    href: "/strategies",
    icon: <AppstoreOutlined />,
    group: "Research",
  },
  {
    key: "data-explorer",
    label: "Data Explorer",
    href: "/data/explorer",
    icon: <DatabaseOutlined />,
    group: "Research",
  },
  {
    key: "data-browser",
    label: "Data Browser",
    href: "/data/browser",
    icon: <StockOutlined />,
    group: "Research",
  },
  {
    key: "data-sources",
    label: "Sources",
    href: "/data/sources",
    icon: <PartitionOutlined />,
    group: "Research",
  },
  {
    key: "alpha-vantage",
    label: "Alpha Vantage",
    href: "/alpha-vantage",
    icon: <LineChartOutlined />,
    group: "Research",
  },
  {
    key: "data-live",
    label: "Live Market",
    href: "/data/live",
    icon: <ThunderboltOutlined />,
    group: "Research",
  },
  {
    key: "factors",
    label: "Factor Workbench",
    href: "/factors",
    icon: <BulbOutlined />,
    group: "Research",
  },
  {
    key: "feature-sets",
    label: "Feature Sets",
    href: "/features",
    icon: <BulbOutlined />,
    group: "Research",
  },
  {
    key: "kg",
    label: "Knowledge Graph",
    href: "/data/kg",
    icon: <NodeIndexOutlined />,
    group: "Research",
  },
  {
    key: "research-equity",
    label: "Equity Research",
    href: "/research",
    icon: <BulbOutlined />,
    group: "Research",
  },
  {
    key: "learn",
    label: "Learn / Taxonomy",
    href: "/learn",
    icon: <BulbOutlined />,
    group: "Research",
  },
  {
    key: "backtest",
    label: "Backtests",
    href: "/backtest",
    icon: <LineChartOutlined />,
    group: "Lab",
  },
  {
    key: "optimizer",
    label: "Optimizer",
    href: "/optimizer",
    icon: <DotChartOutlined />,
    group: "Lab",
  },
  {
    key: "monte-carlo",
    label: "Monte Carlo",
    href: "/monte-carlo",
    icon: <ExperimentOutlined />,
    group: "Lab",
  },
  { key: "ml", label: "ML Training", href: "/ml/training", icon: <FundOutlined />, group: "Lab" },
  {
    key: "ml-models",
    label: "ML Models",
    href: "/ml/models",
    icon: <UnorderedListOutlined />,
    group: "Lab",
  },
  { key: "rl", label: "RL", href: "/rl", icon: <RobotOutlined />, group: "Lab" },
  {
    key: "paper",
    label: "Paper Runs",
    href: "/paper",
    icon: <ThunderboltOutlined />,
    group: "Execution",
  },
  {
    key: "portfolio",
    label: "Portfolio",
    href: "/portfolio",
    icon: <WalletOutlined />,
    group: "Execution",
  },
  {
    key: "monitor",
    label: "Monitor",
    href: "/monitor",
    icon: <MonitorOutlined />,
    group: "Execution",
  },
  {
    key: "crew",
    label: "Crew Trace",
    href: "/crew",
    icon: <RobotOutlined />,
    group: "Execution",
  },
  {
    key: "wf-agent",
    label: "Agent Crew Editor",
    href: "/workflows/agent",
    icon: <NodeIndexOutlined />,
    group: "Workflows",
  },
  {
    key: "wf-data",
    label: "Data Pipeline Editor",
    href: "/workflows/data",
    icon: <NodeIndexOutlined />,
    group: "Workflows",
  },
  {
    key: "wf-strategy",
    label: "Strategy Composer",
    href: "/workflows/strategy",
    icon: <NodeIndexOutlined />,
    group: "Workflows",
  },
  { key: "docs", label: "Docs", href: "/docs", icon: <BulbOutlined />, group: "System" },
  {
    key: "settings",
    label: "Settings",
    href: "/settings",
    icon: <SettingOutlined />,
    group: "System",
  },
];
