"""Automated technical-strategy search with bootstrap synthetic baseline.

Codifies the technique from the Stanford HFT 2016 survey (and similar
notebooks): enumerate a small space of parametrised technical rules,
score each on the historical data, and *also* score each on
**synthetic** time series generated by block-bootstrapping mid-price
changes from the empirical distribution. Only rules whose historical
Sharpe statistically dominates the synthetic null at a chosen
percentile graduate to live emission.

Two surfaces:

- :func:`bootstrap_baseline` — pure helper that returns a Monte-Carlo
  null distribution of Sharpe ratios for a parametric rule. Useful in
  notebooks / analysis flows.
- :class:`BootstrapTechSearchAlpha` — a registered :class:`LobStrategy`
  that, once instantiated with a fitted rule set, emits long / short
  signals based on the best-performing rule. The fit is offline; the
  strategy itself just consults a frozen rule table.

Why a separate strategy and not a flag on existing alphas
=========================================================

The Stanford paper specifically calls out that this *whole pattern*
— enumerate, randomise, dominate — is the alpha. Encoding it as a
dedicated strategy with explicit ``rules`` argument keeps the
search-vs-execute boundary obvious and lets the analysis flow that
fits the rule table live separately.
"""
from __future__ import annotations

from dataclasses import dataclass
import logging
from typing import Any

import numpy as np

from aqp.core.registry import register
from aqp.strategies.lob import LobState, LobStrategy, OrderIntent

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class TechnicalRule:
    """Parameterised technical rule descriptor."""

    name: str
    fast: int
    slow: int
    threshold: float


def _rolling_diff(prices: np.ndarray, fast: int, slow: int) -> np.ndarray:
    """Return the moving-average difference signal (no NaNs at tail)."""
    if prices.size < slow:
        return np.zeros_like(prices)
    fast_ma = np.convolve(prices, np.ones(fast) / fast, mode="same")
    slow_ma = np.convolve(prices, np.ones(slow) / slow, mode="same")
    return fast_ma - slow_ma


def _sharpe_from_pnl(pnl: np.ndarray) -> float:
    if pnl.size < 5:
        return 0.0
    sigma = float(np.std(pnl))
    if sigma < 1e-12:
        return 0.0
    return float(np.mean(pnl) / sigma) * np.sqrt(252.0)


def _block_bootstrap(
    rng: np.random.Generator,
    deltas: np.ndarray,
    n: int,
    block: int,
) -> np.ndarray:
    """Generate a synthetic length-``n`` series by stitching random blocks
    of mid-price changes drawn from ``deltas``."""
    if deltas.size == 0:
        return np.zeros(n)
    n_blocks = int(np.ceil(n / block)) + 1
    starts = rng.integers(0, max(1, deltas.size - block), size=n_blocks)
    chunks = [deltas[s : s + block] for s in starts]
    sample = np.concatenate(chunks)[:n]
    return sample


def bootstrap_baseline(
    prices: np.ndarray,
    *,
    rule: TechnicalRule,
    n_trials: int = 256,
    block: int = 64,
    seed: int = 42,
) -> np.ndarray:
    """Return ``n_trials`` synthetic Sharpe values for ``rule`` under H0.

    H0 = "the directional component of price changes is i.i.d. drawn
    from the empirical distribution". Implemented via block bootstrap
    (Politis & Romano 1994) of the realised mid-price changes.
    """
    rng = np.random.default_rng(seed)
    deltas = np.diff(prices)
    sharpes = np.empty(n_trials, dtype=float)
    for i in range(n_trials):
        synth_deltas = _block_bootstrap(rng, deltas, n=deltas.size, block=block)
        synth_prices = prices[0] + np.cumsum(synth_deltas)
        signal = _rolling_diff(synth_prices, rule.fast, rule.slow)
        positions = np.sign(signal - rule.threshold)
        synth_pnl = positions[:-1] * np.diff(synth_prices)
        sharpes[i] = _sharpe_from_pnl(synth_pnl)
    return sharpes


def evaluate_rule(prices: np.ndarray, rule: TechnicalRule) -> dict[str, float]:
    """Score a single rule on the realised price path."""
    signal = _rolling_diff(prices, rule.fast, rule.slow)
    positions = np.sign(signal - rule.threshold)
    pnl = positions[:-1] * np.diff(prices)
    return {
        "sharpe": _sharpe_from_pnl(pnl),
        "mean": float(np.mean(pnl)),
        "trades": int(np.sum(np.abs(np.diff(positions))) / 2),
    }


def search_rules(
    prices: np.ndarray,
    *,
    rule_space: list[TechnicalRule] | None = None,
    n_trials: int = 256,
    significance: float = 0.99,
    seed: int = 42,
) -> list[dict[str, Any]]:
    """Score every rule in ``rule_space`` and tag survivors.

    Returns a list of ``{rule, sharpe, baseline_p99, survives}`` dicts.
    A rule "survives" iff its realised Sharpe exceeds the chosen
    quantile of the bootstrap-null distribution.
    """
    rules = rule_space or _default_rule_space()
    rng_seed = seed
    out: list[dict[str, Any]] = []
    for rule in rules:
        realised = evaluate_rule(prices, rule)
        baseline = bootstrap_baseline(
            prices, rule=rule, n_trials=n_trials, seed=rng_seed
        )
        rng_seed += 1
        threshold_sharpe = float(np.quantile(baseline, significance))
        out.append(
            {
                "rule": rule,
                "sharpe": realised["sharpe"],
                "mean_pnl": realised["mean"],
                "n_trades": realised["trades"],
                "baseline_quantile": significance,
                "baseline_threshold": threshold_sharpe,
                "survives": realised["sharpe"] > threshold_sharpe,
            }
        )
    return out


def _default_rule_space() -> list[TechnicalRule]:
    """Sensible default rule grid for unit tests + canned demos."""
    fast_set = (5, 10, 20)
    slow_set = (50, 100, 200)
    thresh_set = (0.0, 0.5, 1.0)
    rules: list[TechnicalRule] = []
    for f in fast_set:
        for s in slow_set:
            if s <= f:
                continue
            for t in thresh_set:
                rules.append(
                    TechnicalRule(name=f"ma_{f}_{s}_t{t:g}", fast=f, slow=s, threshold=t)
                )
    return rules


@register(
    "BootstrapTechSearchAlpha",
    source="research_report_2026",
    category="microstructure",
)
class BootstrapTechSearchAlpha(LobStrategy):
    """Trade only rules that statistically beat a bootstrap null.

    Construct with a pre-fitted set of *surviving* rules (see
    :func:`search_rules`). The strategy walks each event, computes the
    rolling fast/slow MA signal for every surviving rule, and emits a
    market order in the direction the **majority** of rules agree on.

    The fit step belongs in an analysis flow / offline notebook;
    instantiating this strategy with an empty rule list is a no-op.
    """

    strategy_id = "bootstrap_tech_search"

    def __init__(
        self,
        rules: list[TechnicalRule] | None = None,
        order_size: float = 1.0,
        max_position: float = 10.0,
        buffer: int = 256,
    ) -> None:
        self.rules: list[TechnicalRule] = list(rules or [])
        self.order_size = float(order_size)
        self.max_position = float(max_position)
        self.buffer = int(buffer)
        self._prices: list[float] = []

    def on_event(self, state: LobState) -> list[OrderIntent]:
        if not self.rules:
            return []
        self._prices.append(state.mid_price)
        if len(self._prices) > self.buffer:
            self._prices = self._prices[-self.buffer :]
        if len(self._prices) < max(r.slow for r in self.rules):
            return []
        prices = np.asarray(self._prices, dtype=float)
        votes = 0
        for rule in self.rules:
            signal = _rolling_diff(prices, rule.fast, rule.slow)
            sig = signal[-1]
            if sig > rule.threshold:
                votes += 1
            elif sig < -rule.threshold:
                votes -= 1
        if votes > 0 and state.position < self.max_position:
            return [
                OrderIntent(
                    side="buy",
                    price=state.best_ask,
                    quantity=self.order_size,
                    order_type="market",
                    time_in_force="ioc",
                    post_only=False,
                    tag="boot_long",
                )
            ]
        if votes < 0 and state.position > -self.max_position:
            return [
                OrderIntent(
                    side="sell",
                    price=state.best_bid,
                    quantity=self.order_size,
                    order_type="market",
                    time_in_force="ioc",
                    post_only=False,
                    tag="boot_short",
                )
            ]
        return []
