"""Render one or more HCL module bodies for the CP-side TerraformRuntime.

The CP runtime consumes a
:class:`aqp_platform_core.models.terraform.TerraformStackSpec` whose
``hcl_modules`` field is a map of *relative path -> rendered HCL*.
The monolith broker or any other caller renders the modules through
this wrapper, drops the result into ``hcl_modules``, and POSTs the
spec to ``/manage/terraform/workspaces/{id}/{plan,apply}``.

Two entry points:

- :func:`render_module` — render one template by ``module_kind`` +
  optional ``cloud_provider``. Returns the HCL body as a string.
- :func:`render_bundle` — render the common ``terraform { ... }``
  header + per-module bodies + a ``locals`` tag block; returns a
  ``{relative_path: hcl_string}`` dict the caller can drop straight
  into :attr:`TerraformStackSpec.hcl_modules`.

The header / variables / outputs renderers mirror
:mod:`aqp.terraform.codegen.wrapper` so the spec hash matches whether
the bundle was produced on the monolith or the CP side.
"""
from __future__ import annotations

import logging
from typing import Any

from aqp_cp.terraform.codegen.base import (
    TEMPLATES_DIR,
    get_environment,
    hcl_value,
)

logger = logging.getLogger(__name__)


def render_module(
    *,
    module_kind: str,
    cloud_provider: str = "local",
    variables: dict[str, Any] | None = None,
    spec_context: dict[str, Any] | None = None,
) -> str:
    """Render one module template.

    Lookup order (so a per-cloud template overrides the generic one):

    1. ``<module_kind>_<cloud_provider>.tf.j2``
    2. ``<module_kind>.tf.j2``

    Returns an empty-string comment when no template matches so the
    caller can decide whether to raise or skip silently.
    """
    env = get_environment()
    candidates = [
        f"{module_kind}_{cloud_provider}.tf.j2",
        f"{module_kind}.tf.j2",
    ]
    ctx = {
        "variables": variables or {},
        "spec": _AttrDict(spec_context or {}),
        "tags": (spec_context or {}).get("tags", {}),
    }
    for name in candidates:
        if (TEMPLATES_DIR / name).exists():
            template = env.get_template(name)
            return template.render(**ctx)
    return f"# No template found for module_kind={module_kind} cloud={cloud_provider}\n"


def render_bundle(
    *,
    stack_name: str,
    workspace_id: str,
    cloud_provider: str,
    modules: list[dict[str, Any]],
    backend_kind: str = "local",
    backend_config: dict[str, Any] | None = None,
    required_providers: dict[str, dict[str, str]] | None = None,
    variables: list[dict[str, Any]] | None = None,
    outputs: list[dict[str, Any]] | None = None,
    common_tags: dict[str, str] | None = None,
) -> dict[str, str]:
    """Render a full HCL bundle ready for ``TerraformStackSpec.hcl_modules``.

    Returns a dict whose keys are workspace-relative paths and whose
    values are rendered HCL strings. The standard bundle is::

        {
          "main.tf":     "<terraform { ... }>\\n<locals>\\n<variables>\\n<outputs>",
          "modules.tf":  "<per-module bodies concatenated>",
        }

    Per-module bodies are rendered via :func:`render_module`. The
    caller can append additional entries to the returned dict for
    free-form HCL the spec needs.
    """
    bundle: dict[str, str] = {}
    main_parts: list[str] = []

    main_parts.append(
        "# Generated by aqp_cp.terraform.codegen — DO NOT EDIT BY HAND."
    )

    # terraform { required_providers + backend } header
    main_parts.append(
        "terraform {\n"
        + _render_required_providers(required_providers)
        + "\n"
        + _render_backend(backend_kind, backend_config or {})
        + "\n}"
    )

    main_parts.append(
        _render_locals(
            stack_name=stack_name,
            workspace_id=workspace_id,
            cloud_provider=cloud_provider,
            extra_tags=common_tags or {},
        )
    )

    if variables:
        main_parts.append(_render_variables(variables))

    if outputs:
        main_parts.append(_render_outputs(outputs))

    bundle["main.tf"] = "\n\n".join(p for p in main_parts if p) + "\n"

    module_bodies: list[str] = []
    for module in modules:
        kind = str(module.get("module_kind") or module.get("kind") or "generic")
        cloud = str(module.get("cloud_provider") or cloud_provider)
        body = render_module(
            module_kind=kind,
            cloud_provider=cloud,
            variables=module.get("variables"),
            spec_context=module.get("spec_context"),
        )
        if body and not body.startswith("# No template found"):
            module_bodies.append(body)
    if module_bodies:
        bundle["modules.tf"] = "\n\n".join(module_bodies) + "\n"

    return bundle


def _render_backend(kind: str, cfg: dict[str, Any]) -> str:
    lines = [f'  backend "{kind}" {{']
    for key, value in cfg.items():
        lines.append(f"    {key} = {hcl_value(value)}")
    lines.append("  }")
    return "\n".join(lines)


def _render_required_providers(
    required_providers: dict[str, dict[str, str]] | None,
) -> str:
    if not required_providers:
        return (
            '  required_providers {\n'
            '    null = { source = "hashicorp/null", version = "~> 3.2" }\n'
            '    random = { source = "hashicorp/random", version = "~> 3.6" }\n'
            "  }"
        )
    parts = ["  required_providers {"]
    for name, attrs in required_providers.items():
        source = attrs.get("source", f"hashicorp/{name}")
        version = attrs.get("version", "")
        version_clause = f', version = "{version}"' if version else ""
        parts.append(
            f'    {name} = {{ source = "{source}"{version_clause} }}'
        )
    parts.append("  }")
    return "\n".join(parts)


def _render_locals(
    *,
    stack_name: str,
    workspace_id: str,
    cloud_provider: str,
    extra_tags: dict[str, str],
) -> str:
    tags = dict(extra_tags)
    tags.setdefault("stack", stack_name)
    tags.setdefault("workspace", workspace_id)
    tags.setdefault("cloud", cloud_provider)
    tags.setdefault("managed-by", "terraform")
    tags.setdefault("control-plane", "aqp_cp")
    body_lines = ["locals {", "  common_tags = {"]
    for key, value in tags.items():
        body_lines.append(f"    {key} = {hcl_value(value)}")
    body_lines.append("  }")
    body_lines.append("}")
    return "\n".join(body_lines)


def _render_variables(variables: list[dict[str, Any]]) -> str:
    blocks: list[str] = []
    for var in variables:
        name = var.get("name")
        if not name:
            continue
        body_lines = [f'variable "{name}" {{']
        body_lines.append(f"  type = {var.get('type', 'string')}")
        if var.get("description"):
            body_lines.append(f"  description = {hcl_value(var['description'])}")
        if var.get("default") is not None:
            body_lines.append(f"  default = {hcl_value(var['default'])}")
        if var.get("sensitive"):
            body_lines.append("  sensitive = true")
        body_lines.append("}")
        blocks.append("\n".join(body_lines))
    return "\n\n".join(blocks)


def _render_outputs(outputs: list[dict[str, Any]]) -> str:
    blocks: list[str] = []
    for out in outputs:
        name = out.get("name")
        value = out.get("value")
        if not name or value is None:
            continue
        body_lines = [f'output "{name}" {{']
        body_lines.append(f"  value = {value}")
        if out.get("description"):
            body_lines.append(f"  description = {hcl_value(out['description'])}")
        if out.get("sensitive"):
            body_lines.append("  sensitive = true")
        body_lines.append("}")
        blocks.append("\n".join(body_lines))
    return "\n\n".join(blocks)


class _AttrDict(dict):
    """Lightweight dot-access shim for spec_context in templates.

    Templates written for the monolith reference ``spec.slug`` /
    ``spec.workspace_id`` — they work unchanged here when the caller
    passes the matching keys in ``spec_context``.
    """

    def __getattr__(self, key: str) -> Any:
        if key in self:
            return self[key]
        raise AttributeError(key)


__all__ = ["render_bundle", "render_module"]
