apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: quantbot-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: quantbot-operator
subjects:
  - kind: ServiceAccount
    name: quantbot-operator
    namespace: aqp-bots
