apiVersion: v1
kind: ServiceAccount
metadata:
  name: quantbot-operator
  namespace: aqp-bots
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: quantbot-bot
  namespace: aqp-bots
automountServiceAccountToken: false
