"""First-class domain model for the Agentic Quant Platform.

This package is the canonical home for every tradable-asset, issuer, event,
market-data, order, fundamentals, ownership, news, and economic primitive in
the platform. It absorbs the best abstractions from four inspirations:

- **gs-quant** — ``(AssetClass, AssetType) -> Instrument`` dispatch, ``XRef``
  identifier flattening, ``PricingContext``/``RiskMeasure`` scaffolding.
- **vnpy** — rich ``ContractData`` with option metadata, ``Offset`` enum for
  futures markets, 5-level ``TickData``, uniform ``*Request`` envelopes.
- **nautilus_trader** — typed identifier value objects (``Venue``,
  ``InstrumentId``, ``ClientOrderId``...), the polymorphic instrument grid
  (``Equity``, ``FuturesContract``, ``OptionContract``, ``CurrencyPair``,
  ``Cfd``, ``CryptoPerpetual``, ``BettingInstrument``, ...), rich order/event
  hierarchy, order-book primitives, option greeks, DeFi scaffolds.
- **OpenBB Platform** — the ``Fetcher[Q,R]`` / ``QueryParams`` / ``Data``
  triad and ~60 ported ``standard_models`` that become the canonical schemas
  for research data.

All legacy ``aqp.core.types`` names (``Symbol``, ``BarData``, ``OrderData``,
``Signal``, ``PortfolioTarget``, ...) continue to work; their internals are
reimplemented as thin facades on top of this module so third-party code that
imports from ``aqp.core`` doesn't have to change.
"""
from __future__ import annotations

from aqp.core.domain.enums import (
    AccountType,
    AggressorSide,
    AssetClass,
    BarAggregation,
    BookAction,
    BookType,
    ContingencyType,
    CorporateActionKind,
    FilingType,
    IndustryClassificationScheme,
    InstrumentClass,
    InstrumentCloseType,
    LiquiditySide,
    MarketStatus,
    Offset,
    OmsType,
    OptionKind,
    OptionStyle,
    OrderSide,
    OrderStatus,
    OrderType,
    PayReceive,
    PositionSide,
    PriceType,
    Product,
    SettlementType,
    TimeInForce,
    TradingState,
    TrailingOffsetType,
    TriggerType,
)
from aqp.core.domain.identifiers import (
    AccountId,
    ActorId,
    ClientId,
    ClientOrderId,
    ComponentId,
    ExecAlgorithmId,
    IdentifierScheme,
    IdentifierSet,
    IdentifierValue,
    InstrumentId,
    OrderListId,
    PositionId,
    StrategyId,
    Symbol2,
    TradeId,
    TraderId,
    Venue,
    VenueOrderId,
)
from aqp.core.domain.money import Currency, Money, Price, Quantity
from aqp.core.domain.instrument import (
    BettingInstrument,
    BinaryOption,
    Bond,
    Cfd,
    Commodity,
    CryptoFuture,
    CryptoOption,
    CryptoPerpetual,
    CryptoToken,
    CurrencyPair,
    Equity,
    ETF,
    FuturesContract,
    FuturesSpread,
    IndexInstrument,
    Instrument,
    InstrumentBase,
    OptionContract,
    OptionSpread,
    PerpetualContract,
    SyntheticInstrument,
    TokenizedAsset,
    instrument_class_for,
    register_instrument_class,
)
from aqp.core.domain.issuer import (
    CorporateEntity,
    EntityKind,
    EntityRelationship,
    EntityRelationshipType,
    Fund,
    GovernmentEntity,
    IndustryClassification,
    Issuer,
    IssuerRef,
    KeyExecutive,
    Location,
    ExecutiveCompensation,
    Sector,
    Industry,
)
from aqp.core.domain.market_data import (
    BarSpecification,
    BarType,
    BookLevel,
    BookOrder,
    FundingRateUpdate,
    ForwardPrice,
    IndexPriceUpdate,
    InstrumentClose,
    InstrumentStatus,
    MarkPriceUpdate,
    OrderBook,
    OrderBookDelta,
    OrderBookDeltas,
    QuoteTick,
    RichSlice,
    TickSnapshot,
    TradeTick,
)
from aqp.core.domain.orders import (
    DomainOrder,
    LimitIfTouchedOrder,
    LimitOrder,
    MarketIfTouchedOrder,
    MarketOrder,
    MarketToLimitOrder,
    OrderAccepted,
    OrderCanceled,
    OrderDenied,
    OrderEmulated,
    OrderExpired,
    OrderFilled,
    OrderInitialized,
    OrderList,
    OrderModifyRejected,
    OrderPendingCancel,
    OrderPendingUpdate,
    OrderRejected,
    OrderReleased,
    OrderSubmitted,
    OrderTriggered,
    OrderUpdated,
    StopLimitOrder,
    StopMarketOrder,
    TrailingStopLimitOrder,
    TrailingStopMarketOrder,
)
from aqp.core.domain.positions import (
    DomainPosition,
    EquityPosition,
    FuturesPosition,
    OptionPosition,
    PositionAdjusted,
    PositionChanged,
    PositionClosed,
    PositionOpened,
    PositionSnapshot,
)
from aqp.core.domain.greeks import (
    BlackScholesResult,
    OptionGreeks,
    OptionGreekValues,
    PortfolioGreeks,
)
from aqp.core.domain.options import (
    OptionChain,
    OptionChainSlice,
    OptionSeriesId,
    StrikeRange,
)
from aqp.core.domain.events import (
    AnalystRatingEvent,
    CorporateActionEvent,
    CotReportEvent,
    DividendDeclarationEvent,
    DomainEvent,
    EarningsEvent,
    EconomicObservationEvent,
    ESGEvent,
    FilingEvent,
    ForwardEstimateEvent,
    IPOEvent,
    InsiderTransactionEvent,
    InstitutionalHoldingEvent,
    MaritimeEvent,
    MergerEvent,
    NewsEvent,
    PoliticianTradeEvent,
    PortVolumeEvent,
    PriceTargetEvent,
    RegulatoryEvent,
    SocialSentimentEvent,
    SplitAnnouncementEvent,
)
from aqp.core.domain.fundamentals import (
    BalanceSheet,
    CashFlowStatement,
    EarningsCallTranscript,
    FinancialRatios,
    FinancialStatement,
    HistoricalDividend,
    HistoricalMarketCap,
    HistoricalSplit,
    IncomeStatement,
    KeyMetrics,
    ManagementDiscussionAnalysis,
    PeriodType,
    ReportedFinancials,
    RevenueBusinessLine,
    RevenueGeographic,
)
from aqp.core.domain.ownership import (
    EquityFtd,
    EquityOwnershipSnapshot,
    EquityPeerGroup,
    Form13FHolding,
    GovernmentTrade,
    InsiderTransaction,
    InstitutionalHolding,
    SharesFloat,
    ShortInterest,
    TopRetail,
)
from aqp.core.domain.calendar_events import (
    CalendarDividend,
    CalendarEarnings,
    CalendarEvents,
    CalendarIpo,
    CalendarSplit,
    EconomicCalendar,
    HalfDay,
    MarketHoliday,
    SpecialSession,
)
from aqp.core.domain.economic import (
    BalanceOfPayments,
    BlsSeries,
    ConsumerConfidence,
    ConsumerPriceIndex,
    CotReport,
    EcbInterestRate,
    EconomicObservation,
    EconomicSeries,
    FederalFundsRate,
    FredObservation,
    FredSeriesMeta,
    GdpForecast,
    GdpNominal,
    GdpReal,
    HousePriceIndex,
    MoneyMeasures,
    NonFarmPayrolls,
    RetailPrices,
    Sofr,
    SoniaRate,
    TreasuryAuction,
    TreasuryPrice,
    TreasuryRate,
    Unemployment,
    YieldCurve,
)
from aqp.core.domain.news import (
    CompanyNews,
    NewsItem,
    Sentiment,
    SentimentLabel,
    WorldNews,
)

__all__ = [
    # enums
    "AccountType",
    "AggressorSide",
    "AssetClass",
    "BarAggregation",
    "BookAction",
    "BookType",
    "ContingencyType",
    "CorporateActionKind",
    "FilingType",
    "IndustryClassificationScheme",
    "InstrumentClass",
    "InstrumentCloseType",
    "LiquiditySide",
    "MarketStatus",
    "Offset",
    "OmsType",
    "OptionKind",
    "OptionStyle",
    "OrderSide",
    "OrderStatus",
    "OrderType",
    "PayReceive",
    "PositionSide",
    "PriceType",
    "Product",
    "SettlementType",
    "TimeInForce",
    "TradingState",
    "TrailingOffsetType",
    "TriggerType",
    # identifiers
    "AccountId",
    "ActorId",
    "ClientId",
    "ClientOrderId",
    "ComponentId",
    "ExecAlgorithmId",
    "IdentifierScheme",
    "IdentifierSet",
    "IdentifierValue",
    "InstrumentId",
    "OrderListId",
    "PositionId",
    "StrategyId",
    "Symbol2",
    "TradeId",
    "TraderId",
    "Venue",
    "VenueOrderId",
    # money
    "Currency",
    "Money",
    "Price",
    "Quantity",
    # instruments
    "BettingInstrument",
    "BinaryOption",
    "Bond",
    "Cfd",
    "Commodity",
    "CryptoFuture",
    "CryptoOption",
    "CryptoPerpetual",
    "CryptoToken",
    "CurrencyPair",
    "ETF",
    "Equity",
    "FuturesContract",
    "FuturesSpread",
    "IndexInstrument",
    "Instrument",
    "InstrumentBase",
    "OptionContract",
    "OptionSpread",
    "PerpetualContract",
    "SyntheticInstrument",
    "TokenizedAsset",
    "instrument_class_for",
    "register_instrument_class",
    # issuer
    "CorporateEntity",
    "EntityKind",
    "EntityRelationship",
    "EntityRelationshipType",
    "ExecutiveCompensation",
    "Fund",
    "GovernmentEntity",
    "Industry",
    "IndustryClassification",
    "Issuer",
    "IssuerRef",
    "KeyExecutive",
    "Location",
    "Sector",
    # market_data
    "BarSpecification",
    "BarType",
    "BookLevel",
    "BookOrder",
    "ForwardPrice",
    "FundingRateUpdate",
    "IndexPriceUpdate",
    "InstrumentClose",
    "InstrumentStatus",
    "MarkPriceUpdate",
    "OrderBook",
    "OrderBookDelta",
    "OrderBookDeltas",
    "QuoteTick",
    "RichSlice",
    "TickSnapshot",
    "TradeTick",
    # orders
    "DomainOrder",
    "LimitIfTouchedOrder",
    "LimitOrder",
    "MarketIfTouchedOrder",
    "MarketOrder",
    "MarketToLimitOrder",
    "OrderAccepted",
    "OrderCanceled",
    "OrderDenied",
    "OrderEmulated",
    "OrderExpired",
    "OrderFilled",
    "OrderInitialized",
    "OrderList",
    "OrderModifyRejected",
    "OrderPendingCancel",
    "OrderPendingUpdate",
    "OrderRejected",
    "OrderReleased",
    "OrderSubmitted",
    "OrderTriggered",
    "OrderUpdated",
    "StopLimitOrder",
    "StopMarketOrder",
    "TrailingStopLimitOrder",
    "TrailingStopMarketOrder",
    # positions
    "DomainPosition",
    "EquityPosition",
    "FuturesPosition",
    "OptionPosition",
    "PositionAdjusted",
    "PositionChanged",
    "PositionClosed",
    "PositionOpened",
    "PositionSnapshot",
    # greeks / options
    "BlackScholesResult",
    "OptionChain",
    "OptionChainSlice",
    "OptionGreekValues",
    "OptionGreeks",
    "OptionSeriesId",
    "PortfolioGreeks",
    "StrikeRange",
    # events
    "AnalystRatingEvent",
    "CorporateActionEvent",
    "CotReportEvent",
    "DividendDeclarationEvent",
    "DomainEvent",
    "EarningsEvent",
    "ESGEvent",
    "EconomicObservationEvent",
    "FilingEvent",
    "ForwardEstimateEvent",
    "IPOEvent",
    "InsiderTransactionEvent",
    "InstitutionalHoldingEvent",
    "MaritimeEvent",
    "MergerEvent",
    "NewsEvent",
    "PoliticianTradeEvent",
    "PortVolumeEvent",
    "PriceTargetEvent",
    "RegulatoryEvent",
    "SocialSentimentEvent",
    "SplitAnnouncementEvent",
    # fundamentals
    "BalanceSheet",
    "CashFlowStatement",
    "EarningsCallTranscript",
    "FinancialRatios",
    "FinancialStatement",
    "HistoricalDividend",
    "HistoricalMarketCap",
    "HistoricalSplit",
    "IncomeStatement",
    "KeyMetrics",
    "ManagementDiscussionAnalysis",
    "PeriodType",
    "ReportedFinancials",
    "RevenueBusinessLine",
    "RevenueGeographic",
    # ownership
    "EquityFtd",
    "EquityOwnershipSnapshot",
    "EquityPeerGroup",
    "Form13FHolding",
    "GovernmentTrade",
    "InsiderTransaction",
    "InstitutionalHolding",
    "SharesFloat",
    "ShortInterest",
    "TopRetail",
    # calendar
    "CalendarDividend",
    "CalendarEarnings",
    "CalendarEvents",
    "CalendarIpo",
    "CalendarSplit",
    "EconomicCalendar",
    "HalfDay",
    "MarketHoliday",
    "SpecialSession",
    # economic
    "BalanceOfPayments",
    "BlsSeries",
    "ConsumerConfidence",
    "ConsumerPriceIndex",
    "CotReport",
    "EcbInterestRate",
    "EconomicObservation",
    "EconomicSeries",
    "FederalFundsRate",
    "FredObservation",
    "FredSeriesMeta",
    "GdpForecast",
    "GdpNominal",
    "GdpReal",
    "HousePriceIndex",
    "MoneyMeasures",
    "NonFarmPayrolls",
    "RetailPrices",
    "Sofr",
    "SoniaRate",
    "TreasuryAuction",
    "TreasuryPrice",
    "TreasuryRate",
    "Unemployment",
    "YieldCurve",
    # news
    "CompanyNews",
    "NewsItem",
    "Sentiment",
    "SentimentLabel",
    "WorldNews",
]
