"""Generate AQP-native Fetcher stubs from builder state.

The generated file is a working `aqp.data.fetchers.Fetcher` subclass
that:

- Registers via :func:`aqp.data.fetchers.register_source_fetcher` so
  it shows up in the manifest pipeline and the metadata cache.
- Resolves credentials through
  :class:`aqp.credentials.CredentialResolver` — never reads
  ``settings.<service>_*`` directly (AGENTS rule 26).
- Delivers a strict `_run` skeleton with TODO markers where the
  user's custom paginator / extractor logic plugs in.

This is the "escape hatch for custom Python" path **without**
``AIRBYTE_ENABLE_UNSAFE_CODE``. Custom logic runs inside AQP under
our credential, lineage, and DataMCPTool guardrails — not inside
Airbyte's worker container.
"""
from __future__ import annotations

import textwrap
from typing import Any

from aqp.data.airbyte.builder.validate import validate_manifest


_TEMPLATE = '''\
"""Generated AQP Fetcher stub for connector ``{connector_id}``.

DO NOT EDIT BY HAND. Generated by
``aqp.data.airbyte.builder.codegen_fetcher`` from the visual
builder. Re-running the generator overwrites this file with the
current builder state.

This is an OUTLINE — production-ready fetchers add Arrow batching,
retry, rate-limit, schema enforcement, and pagination. Use this as
the starting scaffold and follow ``aqp/data/fetchers/api/sec.py`` /
``alpha_vantage.py`` for the polished pattern.
"""
from __future__ import annotations

import logging
from collections.abc import Iterator
from typing import TYPE_CHECKING, Any

import httpx

from aqp.credentials import CredentialKey, get_resolver
from aqp.data.engine.nodes import NodeContext
from aqp.data.fetchers.base import (
    Fetcher,
    FetcherCapability,
    FetcherKind,
    RateLimit,
    register_source_fetcher,
)

logger = logging.getLogger(__name__)

if TYPE_CHECKING:  # pragma: no cover - typing only
    import pyarrow as pa


@register_source_fetcher(
    "source.{connector_id}",
    display_name="{display_name}",
    kind=FetcherKind.API,
    description="Builder-generated fetcher for {display_name}.",
    base_url="{base_url}",
    auth_type="{auth_kind}",
    credentials_ref="{credential_ref}",
    rate_limit=RateLimit(requests_per_second=5),
    capabilities=(FetcherCapability.SUPPORTS_INCREMENTAL.value,),
    domains=("user.dataset",),
)
class {class_name}Fetcher(Fetcher):
    """Builder-generated fetcher stub for {display_name}.

    Replace ``fetch`` with the connector-specific custom logic
    (custom paginator, request signing, retry, schema mapping). The
    default implementation issues a single GET per stream and yields
    one Arrow record batch per response, leaving paging / retry /
    schema enforcement as ``TODO`` for the operator.
    """

    default_rate_limit = RateLimit(requests_per_second=5)

    def __init__(self, *, chunk_rows: int = 1000, **kwargs: Any) -> None:
        super().__init__(chunk_rows=chunk_rows, **kwargs)
        self.chunk_rows = max(1, int(chunk_rows))

    def source_uri(self) -> str | None:
        return "{base_url}"

    def _resolve_credential(self) -> str | None:
        """Return the resolved auth value for ``{auth_kind}`` auth, or None."""
        if "{auth_kind}" == "none":
            return None
        bundle = get_resolver().resolve(
            CredentialKey("{credential_service}", "{credential_account}"),
        )
        value = bundle.get("{credential_field}") or bundle.get("token")
        if not value:
            logger.warning(
                "{connector_id}: credential service=%s account=%s missing field %s",
                "{credential_service}",
                "{credential_account}",
                "{credential_field}",
            )
        return value

    def _build_headers(self, token: str | None) -> dict[str, str]:
        headers: dict[str, str] = {default_headers!r}
        if token:
            if "{auth_kind}" == "bearer":
                headers["Authorization"] = f"Bearer {{token}}"
            elif "{auth_kind}" == "header":
                headers["{auth_header_name}"] = token
        return headers

    def _build_params(self, token: str | None) -> dict[str, Any]:
        params: dict[str, Any] = {default_params!r}
        if token and "{auth_kind}" == "query":
            params["{auth_query_field}"] = token
        return params

    def _stream_records(self, stream_name: str, stream_path: str) -> Iterator[dict[str, Any]]:
        token = self._resolve_credential()
        with httpx.Client(timeout={timeout_s}) as client:
            response = client.request(
                "{method}",
                f"{{self.source_uri()}}/{{stream_path.lstrip('/')}}",
                headers=self._build_headers(token),
                params=self._build_params(token),
            )
            response.raise_for_status()
            payload = response.json()
        cursor: Any = payload
        for segment in {record_path_segments!r}:
            if isinstance(cursor, dict):
                cursor = cursor.get(segment)
            elif isinstance(cursor, list):
                try:
                    cursor = cursor[int(segment)]
                except (ValueError, IndexError):
                    cursor = None
            else:
                cursor = None
        if isinstance(cursor, list):
            yield from cursor
        elif isinstance(cursor, dict):
            yield cursor

    def fetch(self, ctx: NodeContext) -> Iterator[pa.RecordBatch]:
        """Iterate every configured stream and yield Arrow record batches."""
        import pyarrow as pa  # imported lazily to keep import-time cheap

        streams = {streams!r}
        for stream_name, stream_path in streams:
            buffer: list[dict[str, Any]] = []
            for record in self._stream_records(stream_name, stream_path):
                if not isinstance(record, dict):
                    continue
                record["__stream"] = stream_name
                buffer.append(record)
                if len(buffer) >= self.chunk_rows:
                    yield pa.RecordBatch.from_pylist(buffer)
                    buffer = []
            if buffer:
                yield pa.RecordBatch.from_pylist(buffer)


__all__ = ["{class_name}Fetcher"]
'''


def state_to_fetcher_stub(state: dict[str, Any]) -> str:
    """Render the AQP Fetcher stub for ``state``.

    Raises :class:`ValueError` if validation fails — same contract
    as :func:`state_to_yaml`.
    """
    report = validate_manifest(state)
    if report["errors"]:
        raise ValueError(f"manifest validation failed: {report['errors']}")

    metadata = state.get("metadata") or {}
    auth = state.get("auth") or {}
    requester = state.get("requester") or {}
    extractor = state.get("extractor") or {}
    streams = state.get("streams") or []

    connector_id = str(metadata.get("connector_id") or "").strip().lower()
    display_name = str(metadata.get("display_name") or connector_id)
    base_url = str(requester.get("base_url") or "").rstrip("/")
    auth_kind = str(auth.get("auth_kind") or "none").lower()
    credential_ref = str(auth.get("credential_ref") or "").strip()
    credential_service, credential_account, credential_field = _split_credential_ref(credential_ref)
    auth_header_name = str(auth.get("auth_header_name") or "Authorization")
    auth_query_field = str(auth.get("auth_query_field") or "api_key")
    method = str(requester.get("method") or "GET").upper()
    timeout_s = float(requester.get("timeout_s") or 30.0)
    default_headers = dict(requester.get("default_headers") or {})
    default_params = dict(requester.get("default_params") or {})
    record_path = str(extractor.get("record_path") or "$")
    record_path_segments = [seg for seg in record_path.split(".") if seg and seg != "$"]
    stream_pairs = [
        (str(s.get("name") or ""), str(s.get("path") or "")) for s in streams
    ]

    class_name = "".join(part.title() for part in connector_id.replace("-", "_").split("_") if part) or "Generated"

    rendered = _TEMPLATE.format(
        connector_id=connector_id,
        display_name=display_name,
        class_name=class_name,
        base_url=base_url,
        auth_kind=auth_kind,
        credential_ref=credential_ref or "",
        credential_service=credential_service,
        credential_account=credential_account,
        credential_field=credential_field,
        default_headers=default_headers,
        default_params=default_params,
        auth_header_name=auth_header_name,
        auth_query_field=auth_query_field,
        method=method,
        timeout_s=timeout_s,
        record_path_segments=record_path_segments,
        streams=stream_pairs,
    )
    return textwrap.dedent(rendered)


def _split_credential_ref(ref: str) -> tuple[str, str, str]:
    """Parse ``service/account/field`` into a 3-tuple, defaulting account=default field=token."""
    parts = [p.strip() for p in ref.split("/") if p.strip()]
    if len(parts) == 0:
        return ("self_service", "default", "token")
    if len(parts) == 1:
        return (parts[0], "default", "token")
    if len(parts) == 2:
        return (parts[0], parts[1], "token")
    return (parts[0], parts[1], parts[2])


__all__ = ["state_to_fetcher_stub"]
