"""Generate dbt sources and models from AQP metadata."""
from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field
from datetime import date, datetime
from pathlib import Path
from typing import Any

import pandas as pd
import yaml
from sqlalchemy import Table, select

import aqp.persistence as _persistence_models  # noqa: F401 - register all SQLAlchemy tables
from aqp.data import iceberg_catalog
from aqp.data.dbt.project import DbtProjectManager
from aqp.persistence.db import get_session
from aqp.persistence.models import Base

logger = logging.getLogger(__name__)

_GENERATED_HEADER = "-- Generated by AQP dbt exporter. Do not edit by hand.\n"
_EXPORT_TABLES = (
    "dataset_catalogs",
    "dataset_versions",
    "entities",
    "entity_identifiers",
    "entity_relations",
    "entity_annotations",
    "entity_dataset_links",
    "model_versions",
    "feature_sets",
    "feature_set_versions",
)


@dataclass
class DbtExportOptions:
    """Controls for generated dbt exports."""

    include_dataset_models: bool = True
    include_platform_tables: bool = True
    force_project: bool = False
    selected_tables: list[str] = field(default_factory=lambda: list(_EXPORT_TABLES))


@dataclass
class DbtExportResult:
    """Serializable summary of a dbt export pass."""

    files: list[str] = field(default_factory=list)
    models: list[str] = field(default_factory=list)
    sources: list[str] = field(default_factory=list)
    exported_tables: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "files": list(self.files),
            "models": list(self.models),
            "sources": list(self.sources),
            "exported_tables": list(self.exported_tables),
            "warnings": list(self.warnings),
        }


class DbtExporter:
    """Materialize AQP metadata into a generated dbt project."""

    def __init__(self, manager: DbtProjectManager | None = None) -> None:
        self.manager = manager or DbtProjectManager.from_settings()

    def export(self, options: DbtExportOptions | None = None) -> DbtExportResult:
        opts = options or DbtExportOptions()
        result = DbtExportResult()
        project_state = self.manager.ensure_project(force=opts.force_project)
        result.files.extend(project_state.get("written") or [])

        if opts.include_platform_tables:
            self._export_platform_tables(opts, result)
        self._write_sqlalchemy_inventory(result)
        self._write_sources_yml(result)
        if opts.include_dataset_models:
            self._export_dataset_models(result)

        return result

    def _export_platform_tables(self, opts: DbtExportOptions, result: DbtExportResult) -> None:
        selected = [name for name in opts.selected_tables if name in Base.metadata.tables]
        missing = sorted(set(opts.selected_tables) - set(selected))
        result.warnings.extend([f"unknown SQLAlchemy table skipped: {name}" for name in missing])

        with get_session() as session:
            for table_name in selected:
                table = Base.metadata.tables[table_name]
                try:
                    rows = session.execute(select(table)).mappings().all()
                except Exception as exc:  # noqa: BLE001
                    result.warnings.append(f"{table_name}: export failed: {exc}")
                    continue
                records = [_serialize_mapping(row) for row in rows]
                export_path = self.manager.export_dir / f"{table_name}.parquet"
                _write_parquet(records, table, export_path)
                result.files.append(str(export_path))
                result.exported_tables.append(table_name)
                result.sources.append(f"source.aqp_exports.{table_name}")
                model_path = self._write_table_model(table_name)
                result.files.append(str(model_path))
                result.models.append(f"model.aqp_dbt.stg_{_slugify(table_name)}")

    def _write_table_model(self, table_name: str) -> Path:
        model_path = self.manager.generated_models_dir / "platform" / f"stg_{_slugify(table_name)}.sql"
        model_path.parent.mkdir(parents=True, exist_ok=True)
        export_file = (self.manager.export_dir / f"{table_name}.parquet").as_posix()
        model_path.write_text(
            _GENERATED_HEADER
            + "{{ config(materialized='view') }}\n\n"
            + f"select *\nfrom read_parquet('{_sql_escape(export_file)}')\n",
            encoding="utf-8",
        )
        return model_path

    def _write_sqlalchemy_inventory(self, result: DbtExportResult) -> None:
        rows = []
        for table_name, table in sorted(Base.metadata.tables.items()):
            rows.append(
                {
                    "table_name": table_name,
                    "columns": [
                        {
                            "name": column.name,
                            "type": str(column.type),
                            "nullable": bool(column.nullable),
                            "primary_key": bool(column.primary_key),
                        }
                        for column in table.columns
                    ],
                }
            )
        path = self.manager.generated_models_dir / "platform" / "_aqp_sqlalchemy_models.yml"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            yaml.safe_dump(
                {
                    "version": 2,
                    "exposures": [
                        {
                            "name": "aqp_sqlalchemy_models",
                            "type": "analysis",
                            "maturity": "medium",
                            "owner": {"name": "AQP"},
                            "description": "Inventory of SQLAlchemy tables known to AQP.",
                            "meta": {"tables": rows},
                        }
                    ],
                },
                sort_keys=False,
            ),
            encoding="utf-8",
        )
        result.files.append(str(path))

    def _write_sources_yml(self, result: DbtExportResult) -> None:
        tables = [
            {
                "name": table,
                "description": f"Local Parquet export of AQP table {table}.",
                "meta": {
                    "external_location": (self.manager.export_dir / f"{table}.parquet").as_posix(),
                    "generated_by": "aqp.data.dbt.exporter",
                },
            }
            for table in result.exported_tables
        ]
        path = self.manager.generated_models_dir / "sources.yml"
        path.write_text(
            yaml.safe_dump(
                {
                    "version": 2,
                    "sources": [
                        {
                            "name": "aqp_exports",
                            "description": "Generated local AQP metadata snapshots.",
                            "tables": tables,
                        }
                    ],
                },
                sort_keys=False,
            ),
            encoding="utf-8",
        )
        result.files.append(str(path))

    def _export_dataset_models(self, result: DbtExportResult) -> None:
        if "dataset_catalogs" not in Base.metadata.tables:
            return
        dataset_table = Base.metadata.tables["dataset_catalogs"]
        with get_session() as session:
            try:
                rows = session.execute(select(dataset_table)).mappings().all()
            except Exception as exc:  # noqa: BLE001
                result.warnings.append(f"dataset model export failed: {exc}")
                return

        schema_path = self.manager.generated_models_dir / "datasets" / "_datasets.yml"
        schema_models: list[dict[str, Any]] = []
        for row in rows:
            record = dict(row)
            identifier = record.get("iceberg_identifier") or record.get("name") or record.get("id")
            if not identifier:
                continue
            model_name = f"dataset_{_slugify(str(identifier))}"
            sql, warning = self._dataset_sql(record)
            if warning:
                result.warnings.append(warning)
            path = self.manager.generated_models_dir / "datasets" / f"{model_name}.sql"
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(_GENERATED_HEADER + "{{ config(materialized='view') }}\n\n" + sql, encoding="utf-8")
            result.files.append(str(path))
            result.models.append(f"model.aqp_dbt.{model_name}")
            schema_models.append(
                {
                    "name": model_name,
                    "description": f"AQP dataset export for {identifier}.",
                    "meta": {
                        "aqp_dataset_id": record.get("id"),
                        "iceberg_identifier": record.get("iceberg_identifier"),
                        "storage_uri": record.get("storage_uri"),
                        "source_uri": record.get("source_uri"),
                    },
                }
            )

        schema_path.write_text(
            yaml.safe_dump({"version": 2, "models": schema_models}, sort_keys=False),
            encoding="utf-8",
        )
        result.files.append(str(schema_path))

    def _dataset_sql(self, record: dict[str, Any]) -> tuple[str, str | None]:
        identifier = record.get("iceberg_identifier")
        if identifier:
            files = _iceberg_plan_files(str(identifier))
            if files:
                array_lit = ", ".join(f"'{_sql_escape(path)}'" for path in files)
                return f"select *\nfrom read_parquet([{array_lit}], union_by_name=true)\n", None

        for key in ("storage_uri", "source_uri"):
            uri = record.get(key)
            if uri and str(uri).lower().endswith((".parquet", "/*.parquet")):
                return (
                    f"select *\nfrom read_parquet('{_sql_escape(str(uri))}', union_by_name=true)\n",
                    None,
                )

        name = record.get("iceberg_identifier") or record.get("name") or record.get("id")
        value = _sql_escape(str(name))
        return (
            "select *\n"
            "from {{ ref('stg_dataset_catalogs') }}\n"
            f"where coalesce(iceberg_identifier, name, id) = '{value}'\n",
            f"{name}: no data files found; generated metadata-only model",
        )


def _write_parquet(records: list[dict[str, Any]], table: Table, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    columns = [column.name for column in table.columns]
    frame = pd.DataFrame(records, columns=columns)
    frame.to_parquet(path, index=False)


def _serialize_mapping(row: Any) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for key, value in dict(row).items():
        out[str(key)] = _serialize_value(value)
    return out


def _serialize_value(value: Any) -> Any:
    if value is None or isinstance(value, str | int | float | bool):
        return value
    if isinstance(value, datetime | date):
        return value.isoformat()
    if isinstance(value, dict | list | tuple):
        return json.dumps(value, sort_keys=True, default=str)
    return str(value)


def _iceberg_plan_files(identifier: str) -> list[str]:
    try:
        table = iceberg_catalog.load_table(identifier)
        if table is None:
            return []
        scan = table.scan()
        return [str(task.file.file_path) for task in scan.plan_files()]
    except Exception:  # noqa: BLE001
        logger.debug("unable to resolve Iceberg files for %s", identifier, exc_info=True)
        return []


def _slugify(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9_]+", "_", value.strip().lower()).strip("_")
    if not slug:
        return "unnamed"
    if slug[0].isdigit():
        return f"n_{slug}"
    return slug


def _sql_escape(value: str) -> str:
    return value.replace("'", "''")
