"""Core primitives: types, interfaces, indicators, registry, events.

The ``aqp.core`` surface mixes three layers:

- Legacy value types (``Symbol``, ``BarData``, ``OrderData``, …) for
  backward compatibility with strategies, backtest engines, and
  brokerages authored before the domain-model expansion.
- The full :mod:`aqp.core.domain` surface (typed IDs, polymorphic
  ``Instrument`` hierarchy, :class:`Issuer` graph, event/fundamentals/
  ownership/news/economic shapes). All of these are re-exported from
  here so ``from aqp.core import Equity, FilingEvent, BalanceSheet,
  InstrumentId, Fetcher, QueryParams, Data`` works out of the box.
- Framework interfaces (:class:`IStrategy`, :class:`IBrokerage`, …)
  kept stable across releases.
"""

from aqp.core.corporate_actions import (
    AuxiliaryStore,
    FactorFile,
    FactorFileEntry,
    MapFile,
    MapFileEntry,
)
from aqp.core.domain import (
    AccountId,
    ActorId,
    AggressorSide,
    BalanceSheet,
    BarSpecification,
    BarType,
    BettingInstrument,
    BinaryOption,
    Bond,
    BookLevel,
    BookOrder,
    CalendarDividend,
    CalendarEarnings,
    CalendarIpo,
    CalendarSplit,
    CashFlowStatement,
    Cfd,
    ClientOrderId,
    Commodity,
    CompanyNews,
    ContingencyType,
    CorporateActionEvent as DomainCorporateActionEvent,
    CorporateActionKind,
    CorporateEntity,
    CotReport,
    Currency,
    CurrencyPair,
    DomainEvent,
    EarningsCallTranscript,
    EarningsEvent,
    EconomicCalendar,
    EconomicObservation,
    EconomicSeries,
    EntityKind,
    EntityRelationship,
    EntityRelationshipType,
    ETF,
    Equity,
    FederalFundsRate,
    FilingEvent,
    FilingType,
    FinancialRatios,
    IncomeStatement,
    ForwardPrice,
    FredObservation,
    FredSeriesMeta,
    Fund,
    FundingRateUpdate,
    FuturesContract,
    FuturesSpread,
    GovernmentEntity,
    IdentifierScheme,
    IdentifierSet,
    IdentifierValue,
    IndexInstrument,
    IndustryClassification,
    IndustryClassificationScheme,
    InsiderTransaction,
    InsiderTransactionEvent,
    InstitutionalHolding,
    Instrument as DomainInstrument,
    InstrumentClass,
    InstrumentId,
    IPOEvent,
    IssuerRef,
    Issuer as DomainIssuer,
    KeyExecutive,
    KeyMetrics,
    LimitOrder,
    Location,
    MarkPriceUpdate,
    MarketOrder,
    MergerEvent,
    Money,
    NewsEvent,
    NewsItem,
    Offset,
    OptionChain,
    OptionChainSlice,
    OptionContract,
    OptionGreekValues,
    OptionKind,
    OptionStyle,
    OrderBook,
    OrderBookDelta,
    OrderFilled,
    PeriodType,
    PortfolioGreeks,
    Price,
    PriceTargetEvent,
    PriceType,
    Product,
    Quantity,
    QuoteTick,
    RegulatoryEvent,
    SettlementType,
    Sentiment,
    SentimentLabel,
    Sector,
    Industry,
    StopLimitOrder,
    StopMarketOrder,
    Symbol2,
    SyntheticInstrument,
    TickSnapshot,
    TimeInForce,
    TokenizedAsset,
    TradeTick,
    TrailingStopMarketOrder,
    TreasuryRate,
    Venue,
    WorldNews,
    YieldCurve,
    instrument_class_for,
    register_instrument_class,
)
from aqp.core.events import (
    EVENT_AGENT,
    EVENT_BAR,
    EVENT_KILL,
    EVENT_LOG,
    EVENT_ORDER,
    EVENT_POSITION,
    EVENT_RISK,
    EVENT_SIGNAL,
    EVENT_TICK,
    EVENT_TRADE,
    Event,
    EventEngine,
)
from aqp.core.exchange_hours import ExchangeHours, MarketHoursDatabase, default_database
from aqp.core.indicators import (
    ALL_INDICATORS,
    KAMA,
    TRIX,
    AroonOscillator,
    AverageDirectionalIndex,
    AverageTrueRange,
    BollingerBands,
    ChaikinOscillator,
    CommodityChannelIndex,
    DonchianChannel,
    ExponentialMovingAverage,
    HullMovingAverage,
    Indicator,
    IndicatorBase,
    IndicatorDataPoint,
    KeltnerChannels,
    LogReturn,
    MoneyFlowIndex,
    MovingAverageConvergenceDivergence,
    OnBalanceVolume,
    ParabolicSAR,
    RateOfChange,
    RelativeStrengthIndex,
    RollingWindow,
    SimpleMovingAverage,
    StandardDeviation,
    Stochastic,
    UltimateOscillator,
    VolumeWeightedAveragePrice,
    WilliamsPercentR,
    ZScore,
    build_indicator,
    warmup,
)
from aqp.core.interfaces import (
    IAlphaModel,
    IAsyncBrokerage,
    IBrokerage,
    IDataQueueHandler,
    IExchangeHoursDatabase,
    IExecutionModel,
    IFeatureStore,
    IHistoryProvider,
    IIndicator,
    IMarketDataFeed,
    IModel,
    IOrderTicket,
    IPortfolioConstructionModel,
    IResultHandler,
    IRiskManagementModel,
    IStrategy,
    ISubscriptionManager,
    ITimeProvider,
    ITransactionHandler,
    IUniverseSelectionModel,
)
from aqp.core.registry import build_from_config, list_registered, register, resolve
from aqp.core.slice import CorporateActionEvent, Slice
from aqp.core.types import (
    ACTIVE_STATUSES,
    AccountData,
    AssetClass,
    BarData,
    Cash,
    CashBook,
    DataNormalizationMode,
    Direction,
    Exchange,
    Interval,
    OrderData,
    OrderEvent,
    OrderRequest,
    OrderSide,
    OrderStatus,
    OrderTicket,
    OrderType,
    PortfolioTarget,
    PositionData,
    QuoteBar,
    Resolution,
    SecurityHolding,
    SecurityType,
    Signal,
    SubscriptionDataConfig,
    Symbol,
    Tick,
    TickData,
    TickType,
    TradeBar,
    TradeData,
    iter_subscriptions,
    money,
)

from aqp.providers.base import (
    CostTier,
    Data,
    Fetcher,
    QueryParams,
)


__all__ = [
    # Types (scalar)
    "ACTIVE_STATUSES",
    "AccountData",
    "AssetClass",
    "BarData",
    "Cash",
    "CashBook",
    "DataNormalizationMode",
    "Direction",
    "Exchange",
    "Interval",
    "OrderData",
    "OrderEvent",
    "OrderRequest",
    "OrderSide",
    "OrderStatus",
    "OrderTicket",
    "OrderType",
    "PortfolioTarget",
    "PositionData",
    "QuoteBar",
    "Resolution",
    "SecurityHolding",
    "SecurityType",
    "Signal",
    "SubscriptionDataConfig",
    "Symbol",
    "Tick",
    "TickData",
    "TickType",
    "TradeBar",
    "TradeData",
    "money",
    "iter_subscriptions",
    # Slice
    "Slice",
    "CorporateActionEvent",
    # Indicators
    "ALL_INDICATORS",
    "AverageDirectionalIndex",
    "AverageTrueRange",
    "AroonOscillator",
    "BollingerBands",
    "ChaikinOscillator",
    "CommodityChannelIndex",
    "DonchianChannel",
    "ExponentialMovingAverage",
    "HullMovingAverage",
    "Indicator",
    "IndicatorBase",
    "IndicatorDataPoint",
    "KAMA",
    "KeltnerChannels",
    "LogReturn",
    "MoneyFlowIndex",
    "MovingAverageConvergenceDivergence",
    "OnBalanceVolume",
    "ParabolicSAR",
    "RateOfChange",
    "RelativeStrengthIndex",
    "RollingWindow",
    "SimpleMovingAverage",
    "StandardDeviation",
    "Stochastic",
    "TRIX",
    "UltimateOscillator",
    "VolumeWeightedAveragePrice",
    "WilliamsPercentR",
    "ZScore",
    "build_indicator",
    "warmup",
    # Exchange hours
    "ExchangeHours",
    "MarketHoursDatabase",
    "default_database",
    # Corporate actions
    "AuxiliaryStore",
    "FactorFile",
    "FactorFileEntry",
    "MapFile",
    "MapFileEntry",
    # Interfaces
    "IAlphaModel",
    "IAsyncBrokerage",
    "IBrokerage",
    "IDataQueueHandler",
    "IExchangeHoursDatabase",
    "IExecutionModel",
    "IFeatureStore",
    "IHistoryProvider",
    "IIndicator",
    "IMarketDataFeed",
    "IModel",
    "IOrderTicket",
    "IPortfolioConstructionModel",
    "IResultHandler",
    "IRiskManagementModel",
    "IStrategy",
    "ISubscriptionManager",
    "ITimeProvider",
    "ITransactionHandler",
    "IUniverseSelectionModel",
    # Registry
    "build_from_config",
    "list_registered",
    "register",
    "resolve",
    # Events
    "EVENT_AGENT",
    "EVENT_BAR",
    "EVENT_KILL",
    "EVENT_LOG",
    "EVENT_ORDER",
    "EVENT_POSITION",
    "EVENT_RISK",
    "EVENT_SIGNAL",
    "EVENT_TICK",
    "EVENT_TRADE",
    "Event",
    "EventEngine",
    # --- Domain expansion (aqp.core.domain re-exports) -----------------
    # Identifiers
    "AccountId",
    "ActorId",
    "ClientOrderId",
    "IdentifierScheme",
    "IdentifierSet",
    "IdentifierValue",
    "InstrumentId",
    "Symbol2",
    "Venue",
    # Enums (expanded)
    "AggressorSide",
    "ContingencyType",
    "CorporateActionKind",
    "EntityKind",
    "EntityRelationshipType",
    "FilingType",
    "IndustryClassificationScheme",
    "InstrumentClass",
    "Offset",
    "OptionKind",
    "OptionStyle",
    "PeriodType",
    "PriceType",
    "Product",
    "SentimentLabel",
    "SettlementType",
    "TimeInForce",
    # Money
    "Currency",
    "Money",
    "Price",
    "Quantity",
    # Instruments (polymorphic)
    "BettingInstrument",
    "BinaryOption",
    "Bond",
    "Cfd",
    "Commodity",
    "CurrencyPair",
    "DomainInstrument",
    "ETF",
    "Equity",
    "FuturesContract",
    "FuturesSpread",
    "IndexInstrument",
    "OptionContract",
    "SyntheticInstrument",
    "TokenizedAsset",
    "instrument_class_for",
    "register_instrument_class",
    # Issuer graph
    "CorporateEntity",
    "DomainIssuer",
    "EntityRelationship",
    "Fund",
    "GovernmentEntity",
    "Industry",
    "IndustryClassification",
    "IssuerRef",
    "KeyExecutive",
    "Location",
    "Sector",
    # Market data
    "BarSpecification",
    "BarType",
    "BookLevel",
    "BookOrder",
    "ForwardPrice",
    "FundingRateUpdate",
    "MarkPriceUpdate",
    "OrderBook",
    "OrderBookDelta",
    "QuoteTick",
    "TickSnapshot",
    "TradeTick",
    # Orders
    "LimitOrder",
    "MarketOrder",
    "OrderFilled",
    "StopLimitOrder",
    "StopMarketOrder",
    "TrailingStopMarketOrder",
    # Options / greeks
    "OptionChain",
    "OptionChainSlice",
    "OptionGreekValues",
    "PortfolioGreeks",
    # Events
    "DomainCorporateActionEvent",
    "DomainEvent",
    "EarningsEvent",
    "FilingEvent",
    "IPOEvent",
    "InsiderTransactionEvent",
    "MergerEvent",
    "NewsEvent",
    "PriceTargetEvent",
    "RegulatoryEvent",
    # Fundamentals
    "BalanceSheet",
    "CashFlowStatement",
    "EarningsCallTranscript",
    "FinancialRatios",
    "IncomeStatement",
    "KeyMetrics",
    # Ownership
    "InsiderTransaction",
    "InstitutionalHolding",
    # Calendar
    "CalendarDividend",
    "CalendarEarnings",
    "CalendarIpo",
    "CalendarSplit",
    "EconomicCalendar",
    # Economic series
    "CotReport",
    "EconomicObservation",
    "EconomicSeries",
    "FederalFundsRate",
    "FredObservation",
    "FredSeriesMeta",
    "TreasuryRate",
    "YieldCurve",
    # News
    "CompanyNews",
    "NewsItem",
    "Sentiment",
    "WorldNews",
    # Providers pattern
    "CostTier",
    "Data",
    "Fetcher",
    "QueryParams",
]
