{{- if .Values.externalSecrets.enabled -}}
{{- range .Values.externalSecrets.remoteRefs }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ $.Values.externalSecrets.secretStoreRef }}
    kind: ClusterSecretStore
  target:
    name: {{ .name }}
    creationPolicy: Owner
  data:
    {{- range .keys }}
    - secretKey: {{ .envVar }}
      remoteRef:
        key: {{ .remote }}
    {{- end }}
{{- end }}
{{- end }}
