{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "aqp-admin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "aqp-admin.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "aqp-admin.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: api
      interval: {{ .Values.serviceMonitor.interval }}
      path: {{ .Values.serviceMonitor.path }}
{{- end }}
