apiVersion: v1
kind: Service
metadata:
  name: {{ include "aqp-admin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "aqp-admin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: web
      port: 80
      targetPort: web
      protocol: TCP
    - name: api
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector: {{- include "aqp-admin.selectorLabels" . | nindent 4 }}
